<?php
/** Global provider selection. OAuth secrets are never returned to the browser. */
class MMD_RoleManager_Model_AiProvider
{
    const PROVIDER_PATH = 'mmd_ai/provider';
    const AUTH_PATH = 'mmd_ai/openai/oauth_encrypted';
    const OPENAI_MODEL = 'gpt-5.6-sol';
    const CLAUDE_MODEL = 'claude-opus-5';
    const CLAUDE_AUTH_PATH = 'mmd_ai/claude/oauth_encrypted';
    const FALLBACK_PATH = 'mmd_ai/openai/fallback_claude';

    protected function readValue($path)
    {
        $r = Mage::getSingleton('core/resource');
        return (string) $r->getConnection('core_read')->fetchOne(
            $r->getConnection('core_read')->select()->from($r->getTableName('core/config_data'), 'value')
                ->where('scope = ?', 'default')->where('scope_id = ?', 0)->where('path = ?', $path)
        );
    }

    public function isOpenAi()
    {
        return $this->readValue(self::PROVIDER_PATH) === 'openai';
    }

    public function hasOpenAiAuth()
    {
        return $this->readValue(self::AUTH_PATH) !== '';
    }

    public function hasClaudeAuth()
    {
        return $this->readValue(self::CLAUDE_AUTH_PATH) !== '';
    }

    public function usesManagedClient()
    {
        return $this->isOpenAi() || $this->hasClaudeAuth();
    }

    public function isClaudeFallbackEnabled()
    {
        return $this->readValue(self::FALLBACK_PATH) === '1';
    }

    public function configureClaudeBackup($token, $enabled)
    {
        $token = trim((string) $token);
        $replacement = $token !== '';
        if (!$replacement) $token = Mage::helper('core')->decrypt($this->readValue(self::CLAUDE_AUTH_PATH));
        if ($enabled || $replacement) {
            if (!preg_match('/^sk-ant-oat[A-Za-z0-9_-]{70,200}$/D', (string) $token)) {
                throw new DomainException('Enter a Claude subscription OAuth token generated by claude setup-token.');
            }
            if ($this->runClaudeClient('Reply with exactly OK.', '', array(), false, $token) !== 'OK') {
                throw new DomainException('Claude Opus 5 test did not pass. The backup was not changed.');
            }
        }
        if ($replacement) Mage::getConfig()->saveConfig(self::CLAUDE_AUTH_PATH, Mage::helper('core')->encrypt($token), 'default', 0);
        Mage::getConfig()->saveConfig(self::FALLBACK_PATH, $enabled ? '1' : '0', 'default', 0);
        Mage::app()->cleanCache(array('config'));
    }

    public function validateAuth($json)
    {
        if (!is_string($json) || strlen($json) > 65536) {
            throw new DomainException('Upload a Codex OAuth auth.json file smaller than 64 KB.');
        }
        $auth = json_decode($json, true);
        if (!is_array($auth) || !empty($auth['OPENAI_API_KEY']) || ($auth['auth_mode'] ?? 'chatgpt') !== 'chatgpt') {
            throw new DomainException('Use a ChatGPT OAuth login, not an OpenAI API key.');
        }
        $tokens = array();
        foreach (array('access_token', 'refresh_token', 'id_token', 'account_id') as $key) {
            $value = $auth['tokens'][$key] ?? null;
            if (!is_string($value) || $value === '' || strlen($value) > 20000 || preg_match('/[\x00-\x20]/', $value)) {
                throw new DomainException('The OAuth file is incomplete. Sign in to Codex again and export auth.json.');
            }
            $tokens[$key] = $value;
        }
        return json_encode(array('auth_mode' => 'chatgpt', 'OPENAI_API_KEY' => null, 'tokens' => $tokens,
            'last_refresh' => is_string($auth['last_refresh'] ?? null) ? $auth['last_refresh'] : null));
    }

    /** Test before committing either the credentials or the global provider. */
    public function selectProvider($provider, $uploadedAuth = null)
    {
        if (!in_array($provider, array('claude', 'openai'), true)) {
            throw new DomainException('Choose Claude or OpenAI OAuth.');
        }
        if ($provider === 'openai') {
            $saved = $this->readValue(self::AUTH_PATH);
            $auth = $uploadedAuth !== null ? $this->validateAuth($uploadedAuth)
                : $this->validateAuth(Mage::helper('core')->decrypt($saved));
            $result = $this->runClient('Reply with exactly OK.', '', array(), false, $auth);
            if (trim($result) !== 'OK') {
                throw new DomainException('OpenAI connection test did not pass. The provider was not changed.');
            }
            Mage::getConfig()->saveConfig(self::AUTH_PATH, Mage::helper('core')->encrypt($auth), 'default', 0);
        } elseif ($this->hasClaudeAuth() && $this->invokeClaude('Reply with exactly OK.', '', array(), false) !== 'OK') {
            throw new DomainException('Claude Opus 5 test did not pass. Primary provider unchanged.');
        }
        Mage::getConfig()->saveConfig(self::PROVIDER_PATH, $provider, 'default', 0);
        Mage::app()->cleanCache(array('config'));
    }

    public function invoke($prompt, $system = '', array $images = array(), $webSearch = false)
    {
        // Invalid user input is not a provider outage and must never trigger failover.
        if (strlen($prompt) + strlen($system) > 500000 || count($images) > 8) {
            throw new DomainException('The AI request is too large. Shorten the conversation or use fewer images.');
        }
        foreach ($images as $img) {
            $bytes = base64_decode((string) ($img['data'] ?? ''), true);
            $info = $bytes !== false ? @getimagesizefromstring($bytes) : false;
            if (!$info || strlen($bytes) > 5000000 || !in_array($info['mime'], array('image/png', 'image/jpeg', 'image/webp'), true)) {
                throw new DomainException('Reference images must be PNG, JPEG or WebP and under 5 MB.');
            }
        }
        if (!$this->isOpenAi()) return $this->invokeClaude($prompt, $system, $images, $webSearch);
        try {
            return $this->invokeOpenAi($prompt, $system, $images, $webSearch);
        } catch (DomainException $e) {
            if (!$this->isClaudeFallbackEnabled() || !$this->hasClaudeAuth()) throw $e;
            // No prompts, tokens, or raw provider errors in the audit log.
            Mage::log('OpenAI generation unavailable; trying Claude Opus 5 fallback.', Zend_Log::WARN, 'ai-provider.log', true);
            try {
                $answer = $this->invokeClaude($prompt, $system, $images, $webSearch);
                Mage::log('Claude Opus 5 fallback succeeded.', Zend_Log::INFO, 'ai-provider.log', true);
                return $answer;
            } catch (DomainException $fallbackError) {
                throw new DomainException('Both OpenAI and Claude generation failed. Check both OAuth connections in Credentials. No content was sent.');
            }
        }
    }

    protected function invokeClaude($prompt, $system, array $images, $webSearch)
    {
        $token = Mage::helper('core')->decrypt($this->readValue(self::CLAUDE_AUTH_PATH));
        return $this->runClaudeClient($prompt, $system, $images, $webSearch, $token);
    }

    protected function invokeOpenAi($prompt, $system, array $images, $webSearch)
    {
        $saved = $this->readValue(self::AUTH_PATH);
        if ($saved === '') {
            throw new DomainException('OpenAI OAuth is not connected. Ask an administrator to connect it in Credentials.');
        }
        $auth = $this->validateAuth(Mage::helper('core')->decrypt($saved));
        try {
            return $this->runClient($prompt, $system, $images, $webSearch, $auth);
        } finally {
            // Compare-and-swap: an in-flight request must never overwrite a newly imported login.
            $r = Mage::getSingleton('core/resource');
            $r->getConnection('core_write')->update($r->getTableName('core/config_data'),
                array('value' => Mage::helper('core')->encrypt($auth)),
                array('scope = ?' => 'default', 'scope_id = ?' => 0, 'path = ?' => self::AUTH_PATH, 'value = ?' => $saved));
        }
    }

    protected function runClient($prompt, $system, array $images, $webSearch, &$auth)
    {
        if (!is_executable($this->clientBinary())) {
            throw new DomainException('OpenAI client is not installed on this server. Deploy the updated application first.');
        }
        if (strlen($prompt) + strlen($system) > 500000 || count($images) > 8) {
            throw new DomainException('The AI request is too large. Shorten the conversation or use fewer images.');
        }
        $dir = sys_get_temp_dir() . '/mmd-openai-' . bin2hex(random_bytes(16));
        if (!mkdir($dir, 0700)) {
            throw new DomainException('Unable to create a private OpenAI session.');
        }
        $proc = null;
        $pipes = array();
        try {
            $this->privateFile($dir . '/auth.json', $auth);
            $input = array(array('type' => 'text', 'text' => $system . "\n\n" . $prompt));
            $args = array('/usr/bin/timeout', '-k', '5', '110', $this->clientBinary(),
                '/opt/mmd-ai-sdk/bridge.mjs', 'openai', $webSearch ? '1' : '0');
            foreach ($images as $i => $img) {
                $bytes = base64_decode((string) ($img['data'] ?? ''), true);
                $info = $bytes !== false ? @getimagesizefromstring($bytes) : false;
                if (!$info || strlen($bytes) > 5000000 || !in_array($info['mime'], array('image/png', 'image/jpeg', 'image/webp'), true)) {
                    throw new DomainException('Reference images must be PNG, JPEG or WebP and under 5 MB.');
                }
                $path = $dir . '/image-' . $i . '.' . array('image/png' => 'png', 'image/jpeg' => 'jpg', 'image/webp' => 'webp')[$info['mime']];
                $this->privateFile($path, $bytes);
                $input[] = array('type' => 'local_image', 'path' => $path);
            }
            $this->privateFile($dir . '/prompt.json', json_encode($input));
            // Only intentional SDK configuration is inherited; no app/API/environment secrets.
            $env = array('PATH' => '/usr/local/bin:/usr/bin:/bin', 'CODEX_HOME' => $dir);
            $proc = @proc_open($args, array(0 => array('file', $dir . '/prompt.json', 'r'),
                1 => array('pipe', 'w'), 2 => array('pipe', 'w')), $pipes, $dir, $env);
            if (!is_resource($proc)) {
                throw new DomainException('Unable to start the OpenAI client.');
            }
            stream_set_blocking($pipes[1], false);
            stream_set_blocking($pipes[2], false);
            $out = ''; $exit = -1; $deadline = microtime(true) + 118;
            do {
                $out .= stream_get_contents($pipes[1]);
                stream_get_contents($pipes[2]); // Never log provider errors containing credentials/prompts.
                $state = proc_get_status($proc);
                if (!$state['running']) { $exit = $state['exitcode']; break; }
                if (strlen($out) > 2000000) break;
                usleep(100000);
            } while (microtime(true) < $deadline);
            if ($state['running']) proc_terminate($proc, 9);
            $out .= stream_get_contents($pipes[1]);
            $answer = ''; $completed = false;
            foreach (explode("\n", $out) as $line) {
                $event = json_decode($line, true);
                if (($event['type'] ?? '') === 'turn.completed') $completed = true;
                if (($event['type'] ?? '') === 'item.completed' && ($event['item']['type'] ?? '') === 'agent_message') {
                    $answer = (string) ($event['item']['text'] ?? '');
                }
            }
            if ($exit !== 0 || !$completed || trim($answer) === '') {
                throw new DomainException('OpenAI generation failed or timed out. Check the OAuth connection and account access in Credentials. Nothing was sent.');
            }
            return trim($answer);
        } finally {
            if (is_resource($proc)) {
                foreach ($pipes as $pipe) if (is_resource($pipe)) fclose($pipe);
                proc_close($proc);
            }
            if (is_readable($dir . '/auth.json')) {
                try { $auth = $this->validateAuth(file_get_contents($dir . '/auth.json')); } catch (Exception $e) { /* keep validated original */ }
            }
            $this->removePrivateDirectory($dir);
        }
    }

    protected function privateFile($path, $content)
    {
        $file = fopen($path, 'x');
        if (!$file) throw new DomainException('Unable to prepare a private OpenAI session.');
        chmod($path, 0600);
        $written = fwrite($file, $content);
        fclose($file);
        if ($written !== strlen($content)) throw new DomainException('Unable to prepare a private OpenAI session.');
    }

    protected function clientBinary()
    {
        return '/usr/local/bin/node';
    }

    protected function runClaudeClient($prompt, $system, array $images, $webSearch, $token)
    {
        if (!is_executable($this->clientBinary()) || !$token) {
            throw new DomainException('Claude OAuth or its client is unavailable. Check Credentials.');
        }
        $dir = sys_get_temp_dir() . '/mmd-claude-' . bin2hex(random_bytes(16));
        if (!mkdir($dir, 0700)) throw new DomainException('Unable to prepare a private Claude session.');
        $proc = null; $pipes = array();
        try {
            $content = array(array('type' => 'text', 'text' => $system . "\n\n" . $prompt));
            foreach ($images as $img) {
                $info = getimagesizefromstring(base64_decode($img['data'], true));
                $content[] = array('type' => 'image', 'source' => array('type' => 'base64', 'media_type' => $info['mime'], 'data' => $img['data']));
            }
            $input = json_encode(array('type' => 'user', 'message' => array('role' => 'user', 'content' => $content))) . "\n";
            $this->privateFile($dir . '/prompt.jsonl', $input);
            $args = array('/usr/bin/timeout', '-k', '5', '60', $this->clientBinary(),
                '/opt/mmd-ai-sdk/bridge.mjs', 'claude', $webSearch ? '1' : '0');
            $env = array('PATH' => '/usr/local/bin:/usr/bin:/bin', 'CLAUDE_CONFIG_DIR' => $dir,
                'CLAUDE_CODE_OAUTH_TOKEN' => $token, 'DISABLE_AUTOUPDATER' => '1');
            $proc = @proc_open($args, array(0 => array('file', $dir . '/prompt.jsonl', 'r'),
                1 => array('pipe', 'w'), 2 => array('pipe', 'w')), $pipes, $dir, $env);
            if (!is_resource($proc)) throw new DomainException('Unable to start the Claude client.');
            stream_set_blocking($pipes[1], false); stream_set_blocking($pipes[2], false);
            $out = ''; $exit = -1; $deadline = microtime(true) + 68;
            do {
                $out .= stream_get_contents($pipes[1]); stream_get_contents($pipes[2]);
                $state = proc_get_status($proc);
                if (!$state['running']) { $exit = $state['exitcode']; break; }
                if (strlen($out) > 2000000) break;
                usleep(100000);
            } while (microtime(true) < $deadline);
            if ($state['running']) proc_terminate($proc, 9);
            $out .= stream_get_contents($pipes[1]);
            $result = null;
            foreach (explode("\n", $out) as $line) {
                $event = json_decode($line, true);
                if (($event['type'] ?? '') === 'result') $result = $event;
            }
            if ($exit !== 0 || !$result || !empty($result['is_error']) || trim($result['result'] ?? '') === '') {
                throw new DomainException('Claude Opus 5 generation failed or timed out. Check its OAuth connection and account access.');
            }
            return trim($result['result']);
        } finally {
            if (is_resource($proc)) {
                foreach ($pipes as $pipe) if (is_resource($pipe)) fclose($pipe);
                proc_close($proc);
            }
            $this->removePrivateDirectory($dir);
        }
    }

    protected function removePrivateDirectory($dir)
    {
        foreach (new FilesystemIterator($dir, FilesystemIterator::SKIP_DOTS) as $file) {
            if ($file->isDir() && !$file->isLink()) $this->removePrivateDirectory($file->getPathname());
            else unlink($file->getPathname());
        }
        rmdir($dir);
    }
}
