
<?php if(Mage::helper('ExtraConfig')->themeOptions('HOMEBANNER_BANNER_ONE') && Mage::helper('ExtraConfig')->themeOptions('HOMEBANNER_BANNER_ONE') != ''): ?>
<div class="providers">
<div style="height: 135px;" class="latest-corses">
<div style="height: 130px; width: 685px;" class="latest-bgcourses">


<a href="<?php echo Mage::helper('ExtraConfig')->themeOptions('HOMEBANNER_BANNER_ONE_URL'); ?>">
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/homebanner/'.Mage::helper('ExtraConfig')->themeOptions('HOMEBANNER_BANNER_ONE') ?>" alt="Tertiary Courses" width="685" height="130" />
</a>

</div>
</div>
</div>
     <?php endif?>


