-- 1325 : TGS-2026064178 (product 593) -- restore the "CASL - " segment prefix,
--        move the slug to match, and add the course to WSQ Generative AI Courses.
--
--   name : "Create Powerpoint Infographics with AI"
--       -> "CASL - Create Powerpoint Infographics with AI"
--   slug : create-powerpoint-infographics-with-ai
--       -> casl-create-powerpoint-infographics-with-ai
--   + category 379 "WSQ Generative AI Courses"
--
-- Migration 1321 (2026-09-05) DROPPED the CASL prefix from this course; the
-- admin has since asked for it back, with the URL following the name. This is
-- the inverse of 1321 sections 1/2/11/12 -- same shapes, reversed operands.
--
-- SKU is UNCHANGED, so every SkillsFuture / SFEC / SFC / PSEA / UTAP deep link
-- and all five per-SKU cms_blocks (_brochure, _certification, _funding_and_grant,
-- _learning_outcomes, _skills_framework) stay valid and are NOT touched.
--
-- Probed on prod 2026-09-05 -- already correct, so deliberately NOT touched:
--  * CASL badge -- tag_relation already carries tag 289 (CASL); the WSQ tag is
--    already absent. The 2026-07-23 badge-swap rule is satisfied.
--  * SOA / OpenCerts bullet -- the `course_TGS-2026064178_certification` block
--    holds ONLY the "Certificate of Achievement" bullet; the SSG OpenCerts/SOA
--    bullet is already gone (byte-verified, not assumed -- per the multi-variant
--    trap in the CASL playbook). Nothing to remove.
--    NOTE: the PWM ("About Progressive Wage Model") section in `prerequisite`
--    mentions a WSQ Statement of Attainment. That is shared funding boilerplate
--    present on every precedent CASL page -- it STAYS, per the playbook.
--  * cover image -- the admin asked NOT to touch the course image. course_image_url
--    is left exactly as-is. (The renderer strips a leading "CASL"/"WSQ" token
--    anyway, so the existing PNG stays correct for the new name.)
--  * meta_title -- plain title per the Seotitle contract; Seotitle composes the
--    "WSQ funded" prefix at render time for TGS- SKUs. Left alone.
--
-- SG-only. Partner sites (MY/GH) never held this TGS- SKU; @is_sg makes this a
-- no-op there. NOTE: the SG guard COUNT is 2 (unsecure+secure rows), so the
-- test must be `> 0`, never `= 1`.

SET @is_sg := (SELECT COUNT(*) FROM core_config_data
               WHERE path = 'web/unsecure/base_url' AND value LIKE '%tertiarycourses.com.sg%');

SET @e  := (SELECT entity_id FROM catalog_product_entity WHERE sku = 'TGS-2026064178');
SET @et := 4;

SET @a_name    := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=@et AND attribute_code='name');
SET @a_urlkey  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=@et AND attribute_code='url_key');
SET @a_urlpath := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=@et AND attribute_code='url_path');
SET @a_ilabel  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=@et AND attribute_code='image_label');
SET @a_slabel  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=@et AND attribute_code='small_image_label');
SET @a_tlabel  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=@et AND attribute_code='thumbnail_label');

SET @oldname := 'Create Powerpoint Infographics with AI';
SET @newname := 'CASL - Create Powerpoint Infographics with AI';
SET @oldslug := 'create-powerpoint-infographics-with-ai';
SET @newslug := 'casl-create-powerpoint-infographics-with-ai';

SET @genai_cat := 379;   -- WSQ Generative AI Courses

-- ------------------------------------------------------------------ 1. name
-- Guarded on the OLD name so a re-run (or a prior admin edit) never double-
-- prefixes into "CASL - CASL - ...".
UPDATE catalog_product_entity_varchar
   SET value = @newname
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND entity_id = @e AND attribute_id = @a_name
   AND value = @oldname;

-- Image labels + media-gallery label mirror the product name.
UPDATE catalog_product_entity_varchar
   SET value = @newname
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND entity_id = @e
   AND attribute_id IN (@a_ilabel, @a_slabel, @a_tlabel)
   AND value = @oldname;

UPDATE catalog_product_entity_media_gallery_value v
  JOIN catalog_product_entity_media_gallery g ON g.value_id = v.value_id
   SET v.label = @newname
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND g.entity_id = @e AND v.label = @oldname;

-- ------------------------------------------------------------- 2. url_key
UPDATE catalog_product_entity_varchar
   SET value = @newslug
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND entity_id = @e AND attribute_id = @a_urlkey
   AND value = @oldslug;

-- url_path is regenerated by the Catalog URL Rewrites indexer; a stale row wins
-- over the new url_key until then, so drop it at every scope.
DELETE FROM catalog_product_entity_varchar
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND entity_id = @e AND attribute_id = @a_urlpath;

-- ------------------------------------------------ 3. URL rewrites: 301 old->new
-- The is_system=1 row still occupies the OLD bare slug; INSERT IGNORE would
-- silently no-op against it, so delete it FIRST (trap from migration 647).
DELETE FROM core_url_rewrite
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND request_path = CONCAT(@oldslug, '.html')
   AND is_system = 1;

INSERT IGNORE INTO core_url_rewrite
  (store_id, id_path, request_path, target_path, is_system, options)
SELECT s.store_id,
       CONCAT('manual-301-', MD5(CONCAT(@oldslug, '.html')), '-', s.store_id),
       CONCAT(@oldslug, '.html'),
       CONCAT(@newslug, '.html'),
       0, 'RP'
  FROM (SELECT 0 AS store_id UNION ALL SELECT 1) s
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM (SELECT store_id, request_path FROM core_url_rewrite) x
                   WHERE x.request_path = CONCAT(@oldslug, '.html') AND x.store_id = s.store_id);

-- Force any surviving row on the old path to a permanent manual 301.
UPDATE core_url_rewrite
   SET target_path = CONCAT(@newslug, '.html'), options = 'RP', is_system = 0
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND request_path = CONCAT(@oldslug, '.html');

-- Chain-flatten: the ~60 alias rows that already 301 INTO the old slug (the
-- wsq-... and casl-infographics-... generations from 1321 and earlier) must
-- retarget the new slug, or every legacy link becomes a two-hop chain.
-- Anchored on the FULL old filename so no sibling course is swept in.
UPDATE core_url_rewrite
   SET target_path = CONCAT(@newslug, '.html')
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND target_path = CONCAT(@oldslug, '.html')
   AND request_path <> CONCAT(@newslug, '.html');

-- Same flatten for the category-scoped alias rows (…/<category>/<oldslug>.html).
UPDATE core_url_rewrite
   SET target_path = REPLACE(target_path, CONCAT('/', @oldslug, '.html'),
                                          CONCAT('/', @newslug, '.html'))
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND target_path LIKE CONCAT('%/', @oldslug, '.html')
   AND is_system = 0;

-- --------------------------------------------------------- 4. search redirects
-- 34 rows currently point at the old slug. Exact-match only, so the live
-- non-WSQ twin (create-infographics-with-powerpoint.html) is never touched.
UPDATE catalogsearch_query
   SET redirect = CONCAT('https://www.tertiarycourses.com.sg/', @newslug, '.html')
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND redirect = CONCAT('https://www.tertiarycourses.com.sg/', @oldslug, '.html');

-- ------------------------------------- 5. add to "WSQ Generative AI Courses"
-- The course is CASL-funded GenAI-for-PowerPoint content, so it belongs in the
-- funded GenAI listing alongside the two existing CASL members (TGS-2026065050,
-- TGS-2026064709). Appended after the current 17 members.
-- Every member is a funded TGS- SKU, so the category-ordering rule (funded
-- before C-prefix) is satisfied by appending.
INSERT IGNORE INTO catalog_category_product (category_id, product_id, position)
SELECT @genai_cat, @e,
       COALESCE((SELECT MAX(position) FROM (SELECT position FROM catalog_category_product
                                             WHERE category_id = @genai_cat) p), 0) + 1
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND EXISTS (SELECT 1 FROM catalog_category_entity WHERE entity_id = @genai_cat);

-- Mirror into the category index so the listing shows it before the next
-- reindex (a cpc row without an index row renders via anchor inheritance only).
INSERT IGNORE INTO catalog_category_product_index
  (category_id, product_id, position, is_parent, store_id, visibility)
SELECT @genai_cat, @e,
       (SELECT position FROM catalog_category_product
         WHERE category_id = @genai_cat AND product_id = @e),
       1, 1, 4
 WHERE @is_sg > 0 AND @e IS NOT NULL
   AND EXISTS (SELECT 1 FROM catalog_category_entity WHERE entity_id = @genai_cat)
   AND EXISTS (SELECT 1 FROM catalog_category_product
                WHERE category_id = @genai_cat AND product_id = @e);

-- ------------------------------------------------------------ 6. flat mirror
-- Keep the flat table consistent until the next full reindex.
UPDATE catalog_product_flat_1
   SET name = @newname, url_key = @newslug
 WHERE @is_sg > 0 AND @e IS NOT NULL AND entity_id = @e;
