-- C30: rename "Mobile Photography Mastery: Capturing Stunning Photos with Your Phone"
-- -> "Smart Phone Photography Masterclass", and move the slug
-- mobile-photography-mastery-capturing-stunning-photos-with-your-phone
-- -> smart-phone-photography-masterclass with a permanent (301) redirect from
-- every stored old path.
--
-- SG-only course (C-prefix). Guarded on the SG store so this is a no-op on the
-- MY/GH partner servers, which run the same migration chain.
-- Idempotent: safe to re-run.
--
-- Post-deploy (not doable in SQL): refreshProductRewrite(30) + flat reindex,
-- and re-render the R2 cover PNG (the title is baked into the image).

SET @sg  := (SELECT COUNT(*) FROM core_store WHERE store_id = 1 AND code = 'singapore');
SET @pid := (SELECT entity_id FROM catalog_product_entity WHERE TRIM(sku) = 'C30');

SET @old_title := 'Mobile Photography Mastery: Capturing Stunning Photos with Your Phone';
SET @new_title := 'Smart Phone Photography Masterclass';
SET @old_slug  := 'mobile-photography-mastery-capturing-stunning-photos-with-your-phone';
SET @new_slug  := 'smart-phone-photography-masterclass';

-- ---------------------------------------------------------------- name ----
SET @a_name := (SELECT attribute_id FROM eav_attribute a
                JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'name');

UPDATE catalog_product_entity_varchar
SET value = @new_title
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_name;

-- ------------------------------------------------------------ url_key ----
SET @a_urlkey := (SELECT attribute_id FROM eav_attribute a
                  JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                  WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'url_key');

UPDATE catalog_product_entity_varchar
SET value = @new_slug
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_urlkey;

-- url_path is regenerated by the Catalog URL Rewrites indexer, but keep the
-- stored value consistent (store 0 and 1) so a pre-reindex read is not stale.
SET @a_urlpath := (SELECT attribute_id FROM eav_attribute a
                   JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                   WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'url_path');

UPDATE catalog_product_entity_varchar
SET value = CONCAT(@new_slug, '.html')
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_urlpath;

-- ------------------------------------------------------ image labels -----
-- Cover alt/title text; only rows still holding the exact old title.
UPDATE catalog_product_entity_varchar v
JOIN eav_attribute a ON a.attribute_id = v.attribute_id AND a.entity_type_id = 4
 AND a.attribute_code IN ('image_label', 'small_image_label', 'thumbnail_label')
SET v.value = @new_title
WHERE @sg = 1 AND @pid IS NOT NULL
  AND v.entity_id = @pid AND v.value = @old_title;

UPDATE catalog_product_entity_media_gallery_value gv
JOIN catalog_product_entity_media_gallery g ON g.value_id = gv.value_id
SET gv.label = @new_title
WHERE @sg = 1 AND @pid IS NOT NULL
  AND g.entity_id = @pid
  AND (gv.label = @old_title OR gv.label LIKE 'Creating Visual Stories%with Mobile Photography');

-- --------------------------------------------------------- meta data -----
SET @a_mtitle := (SELECT attribute_id FROM eav_attribute a
                  JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                  WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'meta_title');

UPDATE catalog_product_entity_varchar
SET value = 'Smart Phone Photography Masterclass | Tertiary Courses Singapore'
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_mtitle;

-- ------------------------------------------------ short_description -----
-- The intro still quoted an earlier life's title in the first sentence.
SET @a_sdesc := (SELECT attribute_id FROM eav_attribute a
                 JOIN eav_entity_type t ON t.entity_type_id = a.entity_type_id
                 WHERE t.entity_type_code = 'catalog_product' AND a.attribute_code = 'short_description');

UPDATE catalog_product_entity_text
SET value = REPLACE(value, '"Creating Visual Stories with Mobile Photography" course',
                           '"Smart Phone Photography Masterclass" course')
WHERE @sg = 1 AND @pid IS NOT NULL
  AND entity_id = @pid AND attribute_id = @a_sdesc;

-- ------------------------------------------------------- 301 rewrites ----
-- options='RP' IS the 301. Old system rows that served the product are
-- deleted (not repointed) so the indexer can mint the is_system=1 rows for the
-- new slug; bare + category-prefixed old paths are re-added as RP rows below.
--
-- 1) Repoint every existing RP row whose TARGET was an old-slug path, keeping
--    the category prefix flat (one hop, no chain).
UPDATE core_url_rewrite
SET target_path = REPLACE(target_path, CONCAT(@old_slug, '.html'), CONCAT(@new_slug, '.html'))
WHERE @sg = 1
  AND options = 'RP'
  AND (target_path = CONCAT(@old_slug, '.html')
       OR target_path LIKE CONCAT('%/', @old_slug, '.html'));

-- 2) Capture the old system rows' request paths, then delete them.
DROP TEMPORARY TABLE IF EXISTS tmp_c30_old;
CREATE TEMPORARY TABLE tmp_c30_old (store_id SMALLINT, request_path VARCHAR(255));
INSERT INTO tmp_c30_old
SELECT store_id, request_path FROM core_url_rewrite
WHERE @sg = 1 AND @pid IS NOT NULL
  AND product_id = @pid AND is_system = 1
  AND request_path LIKE CONCAT('%', @old_slug, '.html');

DELETE FROM core_url_rewrite
WHERE @sg = 1 AND @pid IS NOT NULL
  AND product_id = @pid AND is_system = 1
  AND request_path LIKE CONCAT('%', @old_slug, '.html');

-- 3) Re-add each old path as a 301 to the matching new path.
INSERT IGNORE INTO core_url_rewrite
  (store_id, id_path, request_path, target_path, is_system, options)
SELECT o.store_id,
       CONCAT('manual-301-', MD5(o.request_path), '-', o.store_id),
       o.request_path,
       REPLACE(o.request_path, CONCAT(@old_slug, '.html'), CONCAT(@new_slug, '.html')),
       0, 'RP'
FROM tmp_c30_old o;

-- 4) Belt and braces: bare old slug -> new slug in store 1.
INSERT IGNORE INTO core_url_rewrite
  (store_id, id_path, request_path, target_path, is_system, options)
SELECT 1, CONCAT('manual-301-', MD5(CONCAT(@old_slug, '.html')), '-1'),
       CONCAT(@old_slug, '.html'), CONCAT(@new_slug, '.html'), 0, 'RP'
FROM DUAL
WHERE @sg = 1
  AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM core_url_rewrite) x
                  WHERE x.request_path = CONCAT(@old_slug, '.html') AND x.store_id = 1);

DROP TEMPORARY TABLE IF EXISTS tmp_c30_old;

-- ------------------------------------------------- search redirects ------
-- Point stored search redirects straight at the new URL (one hop, not two).
UPDATE catalogsearch_query
SET redirect = REPLACE(redirect, CONCAT('/', @old_slug, '.html'), CONCAT('/', @new_slug, '.html'))
WHERE @sg = 1
  AND redirect LIKE CONCAT('%/', @old_slug, '.html');

-- New title as a search term -> C30.
INSERT INTO catalogsearch_query (query_text, num_results, popularity, redirect, store_id, display_in_terms, is_active, is_processed, updated_at)
SELECT @new_title, 1, 1, CONCAT('https://www.tertiarycourses.com.sg/', @new_slug, '.html'), 1, 1, 1, 0, NOW()
FROM DUAL
WHERE @sg = 1
  AND NOT EXISTS (SELECT 1 FROM (SELECT * FROM catalogsearch_query) q
                  WHERE q.query_text = @new_title AND q.store_id = 1);
