-- 1796: clear the GSC "Not found (404)" bucket on www.tertiarycourses.com.sg.
--
-- WHY: GSC validation of 'Not found (404)' FAILED on 2026-10-05 (1,916 URLs). The
-- 1,000-row export was crawled as Googlebot on 2026-10-08: 954 still 404 and they
-- collapse to 564 distinct paths (the rest are ?dir=/?order= variants, which follow
-- the base-path 301 and drop the query). Causes, from prod DB probes:
--   240 retired (disabled) courses still holding their old slug
--   116 system rewrites to products that were deleted/renamed
--    34 deactivated categories
--   145 slugs with no DB trace left (old deleted categories/products)
-- Each slug below 301s to the most relevant LIVE page: a same-name successor
-- course, else the retired course's own deepest live category, else the nearest
-- live parent category, else a topic category (CompTIA/Cisco/LF/... family). Every
-- target was curl-verified 200 with 0 redirects on prod before shipping.
-- 44 slugs stay 404 on purpose (discontinued kids workshops, educational tours,
-- tuition, speed typing: no equivalent page exists, and 404 is the correct answer).
--
-- HOW (the established retire pattern, see 1563 + memory
-- feedback_cross_join_on_duplicate_key_parse_error):
--   1. disabled products / inactive categories owning a slug get url_key
--      '<slug>-retired' so the URL indexer and the boot-time flat-URL job never
--      take the slug back (otherwise a reindex re-points it at the dead entity);
--   2. any old row on the slug (store 0/1) is deleted and replaced by a manual
--      301 row (options='RP', is_system=0, id_path 'gsc404-<md5>');
--   3. existing 301s and search-term redirects that pointed AT a dead slug are
--      repointed straight to its target (no 2-hop chains).
-- SG only (@mms_instance + store guard) -> no-op on MY/GH. Idempotent.

SET @ok := (@mms_instance = 'SG' AND (SELECT COUNT(*) FROM core_store WHERE store_id = 1 AND code = 'singapore') = 1);

DROP TEMPORARY TABLE IF EXISTS tmp_gsc404;
CREATE TEMPORARY TABLE tmp_gsc404 (
  src VARCHAR(255) NOT NULL PRIMARY KEY,
  dst VARCHAR(255) NOT NULL,
  k   VARCHAR(255) NOT NULL DEFAULT ''
) DEFAULT CHARSET=utf8;

INSERT INTO tmp_gsc404 (src, dst) VALUES
('220-1101-a-core-exam-1-cybervista-practice-test.html','comptia-certification-prep-courses.html'),
('3-days-wordpress-specialization-course.html','wordpress-web-deisgn.html'),
('3d-printing-training-courses-in-singapore.html','3d-printing-training-courses.html'),
('3d-printing-workshop-for-kids.html','3d-printing-training-courses.html'),
('3d-printing-workshops-kids-parents.html','3d-printing-training-courses.html'),
('3d-scanning-3d-design-3d-printing-training-in.html','3d-printing-training-courses.html'),
('3d-scanning-training-courses-in-singapore.html','3d-printing-training-courses.html'),
('3ds-max-acp-cert-prep-exam.html','technical-drawing-courses.html'),
('3ds-max-for-architectural-visualization.html','3d-modeling-courses.html'),
('4-days-container-specialization.html','rpa-api-it-automation-courses.html'),
('4-days-excel-specialization.html','microsoft-excel-trainings.html'),
('5-days-blockchain-specialisation.html','ethereum-blockchain-courses.html'),
('5-days-blockchain-specialization.html','blockchain-courses.html'),
('5-days-ci-cd-for-software-development-specialisation.html','devops-courses.html'),
('5-days-cybersecurity-specialization.html','cybersecurity-threat-analysis-courses.html'),
('5-days-digital-marketing-specialization.html','computer-programming-and-infocomm-courses.html'),
('5-days-ethical-hacking-specialization.html','cybersecurity-threat-analysis-courses.html'),
('5-days-full-stack-specialization-course.html','full-stack-web-application-courses.html'),
('5-days-iot-with-rasp-pi-specialization.html','internet-of-things-iot-training-in.html'),
('5-days-machine-learning-specialization.html','computer-programming-and-infocomm-courses.html'),
('5-days-power-platform-specialisation.html','microsoft-power-platform-software-training-courses.html'),
('5-days-python-programming-specialization.html','python-programming.html'),
('5g-wireless-cellular-network.html','networks-training-in.html'),
('8d-approach-to-problem-solving-course.html','quality-and-assurance-training-courses.html'),
('adobe-captivate-essential-training.html','instructional-design-courses.html'),
('adobe-certified-associate-aca.html','adobe-software-training-in.html'),
('adobe-xd-ui-ux-training.html','ux-ui-design-courses.html'),
('adult-training-courses/computer-programming-and-infocomm-courses/data-management-courses/data-engineering-big-data-courses/apache-spark-courses.html','data-engineering-big-data-courses.html'),
('adult-training-courses/life-science-courses-training/wsh-workplace-safety-health-courses.html','healthcare-and-wsh-courses.html'),
('advanced-cyber-security-course.html','cybersecurity-threat-analysis-courses.html'),
('advanced-docker-training.html','docker-courses.html'),
('advanced-google-workspace-training.html','google-g-suite-trainings.html'),
('advanced-iso-keyboard-speed-typing-course.html','business-soft-skills-courses.html'),
('advanced-keras-training.html','python-programming.html'),
('advanced-rpa-training-with-uipath.html','rpa-api-it-automation-courses.html'),
('agent2agent-a2a-protocol-fundamentals.html','computer-programming-and-infocomm-courses.html'),
('agile-and-scrum-courses-1.html','agile-and-scrum-courses.html'),
('ai-agents-courses.html','wsq-ai-agents-courses.html'),
('ai-and-machine-learning-kids-workshops.html','ai-for-machine-learning.html'),
('ai-chatbot-courses.html','chatgpt-and-generative-ai-courses.html'),
('ai-driven-digital-transformation-with-microsoft-365-copilots.html','chatgpt-and-generative-ai-courses.html'),
('ai-ethics-governance-courses-1.html','artificial-intelligence-courses.html'),
('ai-for-finance-1.html','ai-for-finance-courses.html'),
('ai-for-performance-management.html','ai-for-hr-courses.html'),
('ai-for-talent-management.html','ai-for-hr-courses.html'),
('ai-vibe-coding-for-augmented-reality-ar.html','android-programming-courses-in.html'),
('ai-vibe-coding-for-c-sharp.html','c-cplusplus-csharp-training-in.html'),
('ai-vibe-coding-for-dotnet.html','c-cplusplus-csharp-training-in.html'),
('ai-vibe-coding-for-flutter-development.html','ios-xcode-swift-programming-courses.html'),
('ai-vibe-coding-for-google-apps-script.html','rpa-api-it-automation-courses.html'),
('ai-vibe-coding-for-react-native.html','javascript-training-courses-in.html'),
('android-programming-courses-in-singapore.html','android-programming-courses-in.html'),
('angularjs-trainings-in.html','javascript-training-courses-in.html'),
('ansible-courses.html','devops-courses.html'),
('apache-spark-courses-1.html','data-engineering-big-data-courses.html'),
('apache-spark-courses.html','data-engineering-big-data-courses.html'),
('apache-spark-training.html','data-engineering-big-data-courses.html'),
('apply-scrum-methodology-in-agile-enviromment.html','agile-and-scrum-courses.html'),
('apply-workplace-safety-and-health-wsh-in-process-plant.html','healthcare-and-wsh-courses.html'),
('arduino-complete-course-singapore.html','arduino-courses-in.html'),
('arduino-internet-of-things-iot-training.html','internet-of-things-iot-training-in.html'),
('art-media-design-workshops-for-kids.html','digital-media-courses.html'),
('artificial-intelligence-for-kids-courses-and-workshops.html','artificial-intelligence-courses.html'),
('autocad-for-design-and-drafting-autodesk-certified-professional-acp-cert-prep.html','technical-drawing-courses.html'),
('autocad-lt-training.html','technical-drawing-courses.html'),
('autodesk-certified-professional-acp-exam-voucher-1842.html','autodesk-certification-exams.html'),
('autodesk-certified-user-acu-exam-voucher-1840.html','autodesk-certification-exams.html'),
('autodesk-civil-3d-training.html','technical-drawing-courses.html'),
('autodesk-fusion-360-essential-training.html','3d-modeling-courses.html'),
('autodesk-inventor-essential-training.html','3d-modeling-courses.html'),
('autodesk-maya-trainings.html','autodesk-software-courses.html'),
('autodesk-practice-exams.html','autodesk-certification-exams.html'),
('autodesk-revit-structural-training.html','technical-drawing-courses.html'),
('autodesk-revit-training-mep.html','technical-drawing-courses.html'),
('automate-business-processe-with-langflow-agentic-ai.html','ai-for-business.html'),
('automate-business-workflows-with-flowise-agentic-ai.html','programming-courses.html'),
('automating-devops-and-it-workflows-with-ansible.html','rpa-api-it-automation-courses.html'),
('automation-with-google-apps-script-training.html','rpa-api-it-automation-courses.html'),
('aws-assoicate-certification-exam-vouchers.html','certification-exam-prep-courses.html'),
('aws-certification-exam-vouchers-1.html','certification-exam-prep-courses.html'),
('aws-certified-advanced-networking-specialty-ans-c01-exam-prep.html','cloud-computing-courses.html'),
('aws-certified-ai-practitioner-aif-c01-exam-prep.html','cloud-computing-courses.html'),
('aws-certified-cloud-practitioner-exam-prep.html','wsq-aws-certified-cloud-practitioner-training.html'),
('aws-certified-data-engineer-associate-exam-prep.html','wsq-aws-certified-data-engineer-associate-training.html'),
('aws-certified-data-engineer-associate-practice-exams.html','certification-exam-prep-courses.html'),
('aws-certified-developer-associate-exam-prep.html','wsq-aws-certified-developer-associate-training.html'),
('aws-certified-developer-associate-practice-exams.html','certification-exam-prep-courses.html'),
('aws-certified-devops-engineer-professional-practice-exams.html','certification-exam-prep-courses.html'),
('aws-certified-machine-learning-engineer-associate-exam-prep.html','wsq-aws-certified-machine-learning-engineer-associate-training.html'),
('aws-certified-machine-learning-specialty-mls-c01-exam-prep.html','cloud-computing-courses.html'),
('aws-certified-security-specialty-scs-c02-exam-prep.html','cybersecurity-threat-analysis-courses.html'),
('aws-certified-solutions-architect-associate-saa-c03-exam-prep.html','cloud-computing-courses.html'),
('aws-certified-sysops-administrator-associate-soa-c02-practice-exams.html','certification-exam-prep-courses.html'),
('aws-foundational-certification-exam-vouchers.html','certification-exam-prep-courses.html'),
('aws-practice-exams-4.html','certification-exam-prep-courses.html'),
('aws-practice-exams.html','certification-exam-prep-courses.html'),
('aws-skill-builder-individual-yearly-subscription.html','certification-exam-prep-courses.html'),
('aws-skill-builder-team-yearly-subscription.html','certification-exam-prep-courses.html'),
('aws-skill-builder.html','certification-exam-prep-courses.html'),
('aws-specialty-certification-exam-vouchers.html','certification-exam-prep-courses.html'),
('az-120-microsoft-certified-azure-for-sap-workloads-specialty.html','azure-cloud-computing-courses.html'),
('az-140-microsoft-certified-azure-virtual-desktop-specialty.html','azure-cloud-computing-courses.html'),
('az-204-microsoft-azure-developer-associate-exam-prep.html','docker-courses.html'),
('az-305-azure-solutions-architect-expert-exam-prep.html','azure-cloud-computing-courses.html'),
('az-400-designing-and-implementing-microsoft-devops-solutions-exam-prep.html','docker-courses.html'),
('az-500-azure-security-engineer-associate-exam-prep.html','cybersecurity-threat-analysis-courses.html'),
('az-700-azure-network-engineer-associate-exam-prep.html','azure-cloud-computing-courses.html'),
('az-800-microsoft-certified-windows-server-hybrid-administrator-associate.html','azure-cloud-computing-courses.html'),
('azure-machine-learning-courses.html','ai-for-machine-learning.html'),
('basic-docker-training.html','docker-courses.html'),
('basic-excel-training.html','microsoft-excel-trainings.html'),
('basic-flutter-training.html','mobile-programming-courses.html'),
('basic-generative-adversarial-network-gan-training.html','computer-programming-and-infocomm-courses.html'),
('basic-google-analytics-4-ga4-training.html','google-analytics-courses.html'),
('basic-raspberry-pi-and-node-red-training.html','raspberry-pi-courses-in.html'),
('basic-tableau-training.html','data-visualisation-courses.html'),
('bim-revit-and-navisworks.html','technical-drawing-courses.html'),
('blender-3d-and-blender-software-training-courses-in-singapore.html','blender-3d-software-training-in.html'),
('blender-3d-software-training-in-singapore.html','blender-3d-software-training-in.html'),
('build-and-grow-your-e-business-with-magento-2.html','ecommerce-training-courses.html'),
('build-large-language-models-llm-and-deep-learning-applications-with-keras-3.html','deep-learning-computer-vision-courses.html'),
('build-powerful-agentic-ai-workflows-with-langflow-and-mcp.html','computer-programming-and-infocomm-courses.html'),
('build-professional-business-wix-website.html','web-design-courses.html'),
('build-web-apps-with-asp-net-core-and-c-for-beginners.html','programming-courses.html'),
('building-a-scalable-vpn.html','networks-training-in.html'),
('building-live-voice-agents-with-google-s-adk.html','computer-programming-and-infocomm-courses.html'),
('building-mobile-ui-with-flutter.html','mobile-programming-courses.html'),
('business-innovation-with-additive-manufacturing.html','3d-printing-training-courses.html'),
('business-soft-skills-courses-singapore.html','business-soft-skills-courses.html'),
('ccnp-enterprise-implementing-and-operating-cisco-enterprise-network-core-technologies-350-401-encor-exam-prep.html','networks-training-in.html'),
('ccnp-enterprise-implementing-cisco-enterprise-advanced-routing-and-services-300-410-enarsi-exam-prep.html','networks-training-in.html'),
('cert-prep-autodesk-inventor.html','technical-drawing-courses.html'),
('certification-exam-prep-courses/autodesk-certification-exams/autodesk-practice-exams.html','autodesk-certification-exams.html'),
('certification-exam-prep-courses/comptia-certification-prep-courses/comptia-practice-exams.html','comptia-certification-prep-courses.html'),
('certification-exam-prep-courses/microsoft-certifications-exams/microsoft-practice-exams.html','microsoft-certifications-exams.html'),
('certification-exam-prep-courses/pearson-vue-it-specialists/pearson-vue-it-specialist-exam-vouchers.html','certification-exam-prep-courses.html'),
('certified-information-systems-auditor-cisa-exam-prep.html','others-certification-exam-prep.html'),
('certified-kubernetes-security-specialist-cks-prep.html','linux-foundation-certification-exam-prep-courses.html'),
('certmaster-perform-for-cloudnetx-cnx-001-self-paced.html','comptia-certification-prep-courses.html'),
('certmaster-perform-for-datax-dy0-001-self-paced.html','comptia-certification-prep-courses.html'),
('certmaster-perform-network-n10-009-self-paced.html','comptia-certification-prep-courses.html'),
('certprep-courseware-html5-application-development-inf-306-self-paced.html','full-stack-web-application-courses.html'),
('certprep-courseware-it-specialist-artificial-intelligence-self-paced.html','artificial-intelligence-courses.html'),
('certprep-courseware-it-specialist-cloud-computing-self-paced.html','cloud-computing-courses.html'),
('certprep-courseware-it-specialist-computational-thinking-self-paced.html','certification-exam-prep-courses.html'),
('certprep-courseware-it-specialist-cybersecurity-self-paced.html','certification-exam-prep-courses.html'),
('certprep-courseware-it-specialist-data-analytics-self-paced-inf-202-180-day-access.html','data-analytics-courses.html'),
('certprep-courseware-it-specialist-html-and-css-self-paced.html','certification-exam-prep-courses.html'),
('certprep-courseware-it-specialist-java-self-paced.html','certification-exam-prep-courses.html'),
('certprep-courseware-it-specialist-javascript-self-paced.html','certification-exam-prep-courses.html'),
('certprep-courseware-it-specialist-network-security-self-paced.html','wsq-it-security-courses.html'),
('certprep-courseware-it-specialist-networking-self-paced.html','certification-exam-prep-courses.html'),
('certprep-courseware-it-specialist-software-development-self-paced.html','certification-exam-prep-courses.html'),
('chatgpt-and-generative-ai-courses-1.html','chatgpt-and-generative-ai-courses.html'),
('cisco-ccnp-encor-practice-exams.html','cisco-certification-exam-prep.html'),
('cisco-practice-exams.html','cisco-certification-exam-prep.html'),
('cissp-practice-exams.html','isc2-certification-exam-prep-courses.html'),
('citrep-data-science-ai-courses.html','artificial-intelligence-courses.html'),
('civil-3d-for-infrastructure-design-autodesk-certified-professional-acp-cert-prep.html','technical-drawing-courses.html'),
('claude-ai-for-digital-marketing.html','google-cloud-platform-courses.html'),
('cloud-computing-practice-exams.html','cloud-computing-courses.html'),
('coaching-and-mentoring-courses.html','business-soft-skills-courses.html'),
('communication.html','communication-courses.html'),
('company-group-training-enquiry.html','corporate-training.html'),
('comptia-casp-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-cloud-cv0-004-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-a-core-1-220-1101-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-a-core-2-220-1102-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-casp-cas-004-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-cloud-essentials-clo-002-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-data-da0-001-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-datasys-ds0-001-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-it-fundamentals-itf-fc0-u61-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-project-pk0-005-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-for-security-sy0-701-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-network-n10-009-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-learn-tech-fc0-u71-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-certmaster-perform-securityx-casp-cas-005-self-paced.html','comptia-certification-prep-courses.html'),
('comptia-cloud-essentials-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-cloud-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-cloud-practice-exams.html','comptia-certification-prep-courses.html'),
('comptia-cysa-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-data-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-data-practice-exams.html','comptia-certification-prep-courses.html'),
('comptia-datax-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-itf-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-linux-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-linux-practice-exams.html','comptia-certification-prep-courses.html'),
('comptia-network-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-pentest-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-pentest-practice-exams.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-49.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-51.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-52.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-53.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-54.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-62.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-65.html','comptia-certification-prep-courses.html'),
('comptia-practice-exams-68.html','comptia-certification-prep-courses.html'),
('comptia-security-practice-exams.html','comptia-certification-prep-courses.html'),
('comptia-self-paced-e-learning-courses.html','comptia-certification-prep-courses.html'),
('comptia-server-exam-vouchers.html','comptia-certification-prep-courses.html'),
('comptia-server-practice-exams.html','comptia-certification-prep-courses.html'),
('costing-essentials-finance-professionals.html','finance-courses.html'),
('cplusplus-essential-training-in.html','c-cplusplus-csharp-training-in.html'),
('create-ai-agent-with-gemini-cli.html','computer-programming-and-infocomm-courses.html'),
('create-email-marketing-campaigns-that-turn-leads-into-customers.html','email-marketing-courses-in.html'),
('creating-compelling-videos-with-ai-and-generative-ai-gai.html','video-micro-drama-courses.html'),
('creating-dynamic-elearning-content-with-ispring-suite.html','instructional-design-courses.html'),
('creating-serverless-agentic-workflows-with-amazon-bedrock.html','cloud-computing-courses.html'),
('creating-smart-solutions-with-iot-and-microcontroller-coding.html','internet-of-things-iot-training-in.html'),
('critical-core-skills-courses.html','thinking-critically-critical-core-skills-courses.html'),
('critical-core-soft-skills-courses-1.html','thinking-critically-critical-core-skills-courses.html'),
('critical-core-soft-skills-courses.html','business-soft-skills-courses.html'),
('crypto-nft-defi-gamefi-tokenomics-fundamentals.html','ethereum-blockchain-courses.html'),
('cyber-security-certification-prep-courses.html','wsq-cyber-security-pdpa-courses.html'),
('cybersecurity-threat-analysis-courses-1.html','cybersecurity-threat-analysis-courses.html'),
('data-analytics-data-visualization-training.html','wsq-data-analytics-wsq-courses.html'),
('data-mining-training-rapidminer-studio.html','data-management-courses.html'),
('data-visualisation-with-google-data-studio.html','data-visualisation-courses.html'),
('data-visualisation-with-python-training.html','data-visualisation-courses.html'),
('data-visualization-training-courses.html','wsq-data-analytics-wsq-courses.html'),
('database-training-microsoft-access.html','database.html'),
('deep-learning-nlp-courses.html','deep-learning-computer-vision-courses.html'),
('deep-reinforcement-learning-course.html','deep-reinforcement-learning-courses.html'),
('deep-reinforcement-with-python.html','deep-reinforcement-learning-courses.html'),
('devops-and-workflow-management-with-argo-lfs256.html','linux-foundation-certification-exam-prep-courses.html'),
('devops-essential-training.html','devops-courses.html'),
('digital-ic-design-courses-1.html','electronics-semiconductor-training-courses.html'),
('digital-ic-design-courses.html','electronics-coures.html'),
('digital-transformation-with-metaverse-and-web-3-0.html','metaverse-courses.html'),
('dp-300-azure-database-administrator-associate.html','relational-sql-databases.html'),
('dp-602t00-implement-a-data-warehouse-with-microsoft-fabric-1691.html','microsoft-fabric-courses.html'),
('dp-603t00-implement-a-real-time-intelligence-solution-with-microsoft-fabric.html','microsoft-fabric-courses.html'),
('dp-604t00-implement-a-data-science-and-machine-learning-solution-with-microsoft-fabric.html','microsoft-fabric-courses.html'),
('ecommerce-marketplaces-courses.html','ecommerce-training-courses.html'),
('ecommerce-with-wordpress.html','wordpress-web-deisgn.html'),
('effective-data-quality-management-frameworks-for-data-driven-decision-making.html','data-quality-management-courses.html'),
('elastic-search-kibana-courses-1.html','elastic-search-kibana-courses.html'),
('elasticsearch-kibana-training.html','elastic-search-kibana-courses.html'),
('electronics-mechatronics-robotics-courses-in-singapore.html','iot-robotics-courses-in.html'),
('enquiries/corporate-training/company-group-training-enquiry.html','corporate-training.html'),
('enterprise-lan-essentials-training.html','networks-training-in.html'),
('esg-and-sustainability-courses-1.html','esg-and-sustainability-courses.html'),
('ethereum-smart-contract-course.html','ethereum-blockchain-courses.html'),
('ethereum-smart-contract-programming-solidity-web3.html','ethereum-blockchain-courses.html'),
('excel-dashboards-business-analytics.html','data-visualisation-courses.html'),
('excel-for-trading-and-investment.html','microsoft-excel-trainings.html'),
('facebook-advertising-training.html','facebook-marketing-advertisting-courses.html'),
('finance-courses-1.html','finance-courses.html'),
('fine-tuning-llm-model-to-supercharge-your-model.html','computer-programming-and-infocomm-courses.html'),
('five-day-semiconductor-specialization-bootcamp.html','semiconductor-devices-fabrication-courses.html'),
('flutter-courses.html','mobile-programming-courses.html'),
('fpga-designer-training.html','electronics-coures.html'),
('full-autodesk-fusion-360-training.html','technical-drawing-courses.html'),
('full-c-programming-training.html','c-cplusplus-csharp-training-in.html'),
('full-machine-learning-with-r.html','r-programming-courses-in.html'),
('full-r-bioconductor-training.html','r-programming-courses-in.html'),
('fundamentals-of-iso-50001-2018-energy-management-system.html','iso-standards-courses.html'),
('fusion-360-design-for-manufacturing-professional-acp-certification-prep.html','technical-drawing-courses.html'),
('game-development-certification-prep-courses.html','gaming-animation-and-video-courses-in.html'),
('gaming-software-courses.html','gaming-animation-and-video-courses-in.html'),
('gen-ai-music-songs-for-kids.html','chatgpt-and-generative-ai-courses.html'),
('genai-3d-modeling-for-kids.html','3d-modeling-courses.html'),
('genai-coding-for-kids.html','ai-vibe-coding-series.html'),
('genai-for-kids-boost-creativity-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-boosting-self-confidence-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-building-interactive-web-apps-with-vibe-coding.html','ai-vibe-coding-series.html'),
('genai-for-kids-conversational-mandarin-with-genai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-crafting-your-first-storybook-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-create-comics-and-manga-with-genai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-create-your-own-ai-avatar-video-with-gen-ai.html','genai-video-creation.html'),
('genai-for-kids-creating-animated-short-video-clip-with-gen-ai.html','genai-video-creation.html'),
('genai-for-kids-creating-engaging-presentation-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-creating-engaging-videos-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-creating-music-and-songs-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-generating-creative-visual-arts-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-intermediate-python-programming-with-vibe-coding.html','python-programming.html'),
('genai-for-kids-learn-basic-phonics-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-learn-basic-programming-concepts-with-genai.html','ai-vibe-coding-series.html'),
('genai-for-kids-learn-english-grammar-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-make-chemistry-fun-for-kids-with-genai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-master-prompting-to-generate-better-content.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-problem-solving-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('genai-for-kids-understanding-and-solving-math-problems-with-gen-ai.html','chatgpt-and-generative-ai-courses.html'),
('generative-adversarial-network-gan.html','chatgpt-and-generative-ai-courses.html'),
('generative-ai-for-curriculum-development.html','instructional-design-courses.html'),
('generative-ai-for-linkedin-lead-generation.html','social-media-marketing-training-courses.html'),
('generative-ai-gai-for-finance.html','ai-for-finance-courses.html'),
('generative-ai-gai-llm-courses-1.html','wsq-generative-ai-courses.html'),
('generative-ai-with-video-editing.html','video-micro-drama-courses.html'),
('github-actions-certification-prep.html','git-and-github-courses.html'),
('github-administration-certification-prep.html','git-and-github-courses.html'),
('github-advanced-security-certification-prep.html','git-and-github-courses.html'),
('github-copilot-certification-prep.html','git-and-github-courses.html'),
('google-adwords-essential-training-course.html','digital-advertising-ppc-courses.html'),
('google-apps-script-courses.html','rpa-api-it-automation-courses.html'),
('google-associate-cloud-engineer-practice-exams.html','google-cloud-certification-prep-courses.html'),
('google-classroom-lms-training.html','instructional-design-courses.html'),
('google-cloud-practice-exams.html','google-cloud-certification-prep-courses.html'),
('google-data-studio-courses.html','data-visualisation-courses.html'),
('google-professional-cloud-database-engineer-certification-exam-prep.html','google-cloud-platform-courses.html'),
('google-professional-cloud-devops-engineer-certification-prep.html','google-cloud-platform-courses.html'),
('google-professional-cloud-network-engineer-certification-prep.html','google-cloud-platform-courses.html'),
('google-professional-cloud-security-engineer-certification-prep.html','cybersecurity-threat-analysis-courses.html'),
('google-professional-data-engineer-certification-prep.html','google-cloud-platform-courses.html'),
('google-sheets-training.html','google-g-suite-trainings.html'),
('google-software-training-in-1.html','google-software-training-in.html'),
('google-tag-manager-gtm-training.html','google-analytics-courses.html'),
('google-workspace-training-in.html','google-g-suite-trainings.html'),
('graphics-design-courses-1.html','graphics-design-courses.html'),
('healthcare-courses.html','healthcare-and-wsh-courses.html'),
('how-to-create-and-sell-non-fungible-token-nft-without-coding.html','non-fungible-tokens-nft-courses.html'),
('how-to-setup-a-successful-online-store.html','ecommerce-training-courses.html'),
('hyperledger-fabric-certified-practitioner-hfcp-prep.html','linux-foundation-certification-exam-prep-courses.html'),
('hyperledger-fabric-design-develop-and-deploy-lfs270.html','linux-foundation-certification-exam-prep-courses.html'),
('ibf-fts-cyber-security-courses.html','wsq-cyber-security-pdpa-courses.html'),
('ibf-fts-data-storytelling-visualisation-courses.html','data-visualisation-courses.html'),
('icdl-microsoft-office-wsq-courses.html','microsoft-365-software-training.html'),
('iib-council-certified-blockchain-professional-course-11.html','blockchain-courses.html'),
('iib-council-certified-blockchain-professional-course-28.html','blockchain-courses.html'),
('image-classification-keras.html','python-programming.html'),
('intermediate-iso-keyboard-speed-typing-course.html','business-soft-skills-courses.html'),
('investment-courses-in.html','fintech-courses.html'),
('ipv4-masterclass.html','networks-training-in.html'),
('isc2-isaca-practice-exams.html','isc2-certification-exam-prep-courses.html'),
('iso-14001-2015-ems-internal-auditor-training.html','iso-standards-courses.html'),
('iso-14001-2015-environment-management-system.html','iso-standards-courses.html'),
('iso-14064-internal-auditor-training.html','wsq-iso-14064-internal-auditor-training.html'),
('iso-22301-business-continuity-management-system.html','iso-standards-courses.html'),
('iso-27001-information-security-management-system.html','iso-standards-courses.html'),
('iso-37001-anti-bribery-management-system.html','iso-standards-courses.html'),
('iso-45001-2018-occupational-health-safety-management-system.html','iso-standards-courses.html'),
('iso-50001-2018-energy-management-system.html','iso-standards-courses.html'),
('iso-iec-20000-1-2018-service-management-system.html','iso-standards-courses.html'),
('itil-4-practice-exams.html','itil-4-certification-exam-prep-courses.html'),
('javascript-for-interactive-website-essential-training-in.html','javascript-training-courses-in.html'),
('kubernetes-for-developers-lfd259.html','linux-foundation-certification-exam-prep-courses.html'),
('kubernetes-fundamentals-lfs258.html','linux-foundation-certification-exam-prep-courses.html'),
('laravel-essential-training.html','programming-courses.html'),
('large-language-model-llm-courses.html','chatgpt-and-generative-ai-courses.html'),
('linear-programming-optimisation-course.html','data-analytics-courses.html'),
('linux-foundation-certified-it-associate-lfca-prep.html','linux-foundation-certification-exam-prep-courses.html'),
('linux-foundations-self-paced-e-learning-courses.html','linux-foundation-certification-exam-prep-courses.html'),
('linux-operating-system-training.html','linux-courses.html'),
('magento-training-courses-in.html','ecommerce-training-courses.html'),
('mastering-corporate-law-compliance-for-business-growth.html','corporate-governance-courses.html'),
('mastering-iot-for-business-innovation.html','internet-of-things-iot-training-in.html'),
('mastering-responsive-web-design-for-modern-websites.html','html-css-training-courses.html'),
('mastering-screen-writing-with-generative-ai-genai.html','chatgpt-and-generative-ai-courses.html'),
('maya-essential-training-in-singapore.html','3d-modeling-courses.html'),
('mb-230-microsoft-certified-dynamics-365-customer-service-functional-consultant-associate.html','microsoft-certifications-exams.html'),
('mb-280-microsoft-certified-dynamics-365-customer-experience-analyst-associate.html','microsoft-certifications-exams.html'),
('mb-330-microsoft-certified-dynamics-365-supply-chain-management-functional-consultant-associate.html','microsoft-certifications-exams.html'),
('mb-335-microsoft-certified-dynamics-365-supply-chain-management-functional-consultant-expert.html','microsoft-certifications-exams.html'),
('mb-800-microsoft-certified-dynamics-365-business-central-functional-consultant-associate.html','microsoft-certifications-exams.html'),
('mb-910-microsoft-dynamics-365-fundamentals-crm-exam-prep.html','computer-programming-and-infocomm-courses.html'),
('mb-920-microsoft-dynamics-365-fundamentals-erp.html','microsoft-certifications-exams.html'),
('microbit-courses-singapore.html','iot-robotics-courses-in.html'),
('microsoft-365-administrator-training-ms-102.html','microsoft-365-software-training.html'),
('microsoft-365-certified-endpoint-administrator-associate-md-102-practice-exams.html','microsoft-certifications-exams.html'),
('microsoft-azure-enterprise-data-analyst-associate-exam-prep.html','azure-cloud-computing-courses.html'),
('microsoft-certification-exam-vouchers-1.html','microsoft-certifications-exams.html'),
('microsoft-certification-exam-vouchers.html','microsoft-certifications-exams.html'),
('microsoft-certified-azure-administrator-associate-az-104-practice-exams.html','microsoft-certifications-exams.html'),
('microsoft-certified-azure-data-engineer-associate-dp-203-practice-exams.html','microsoft-certifications-exams.html'),
('microsoft-certified-azure-developer-associate-az-204-practice-exams.html','microsoft-certifications-exams.html'),
('microsoft-certified-azure-fundamentals-az-900-practice-exams.html','microsoft-certifications-exams.html'),
('microsoft-certified-devops-engineer-expert-az-400-practice-exams.html','microsoft-certifications-exams.html'),
('microsoft-certified-power-platform-fundamentals-pl-900-practice-exams.html','microsoft-power-platform-software-training-courses.html'),
('microsoft-office-specialist-excel-associate-mo-200-exam-prep.html','microsoft-excel-trainings.html'),
('microsoft-onedrive-for-personal-and-business-training.html','microsoft-365-software-training.html'),
('microsoft-onedrive-software-training.html','microsoft-365-software-training.html'),
('microsoft-sharepoint-online-essential-training.html','microsoft-sharepoint-software-training.html'),
('microsoft-software-training-in-singapore.html','microsoft-software-training.html'),
('microsoft-windows-10-training.html','linux-courses.html'),
('mobile-apps-kids-workshops.html','mobile-programming-courses.html'),
('mongodb-essential-training.html','nosql-courses.html'),
('ms-102-microsoft-365-administrator-exam-prep.html','microsoft-365-software-training.html'),
('ms-102-microsoft-365-administrator-practice-exams.html','microsoft-certifications-exams.html'),
('ms-4002-prepare-security-and-compliance-to-support-microsoft-365-copilot.html','cyber-security-digital-forensic-training-courses.html'),
('ms-4004-empower-your-workforce-with-microsoft-365-copilot-use-cases.html','chatgpt-and-generative-ai-courses.html'),
('ms-4005-craft-effective-prompts-for-microsoft-365-copilot.html','chatgpt-and-generative-ai-courses.html'),
('ms-4007-microsoft-365-copilot-user-enablement-specialist.html','chatgpt-and-generative-ai-courses.html'),
('ms-600-microsoft-365-certified-teams-application-developer-associate-exam-prep-2204.html','microsoft-software-training.html'),
('muse-courses.html','web-design-courses.html'),
('name-microsoft-certified-power-bi-data-analyst-associate-pl-300-practice-exams.html','microsoft-certifications-exams.html'),
('natural-language-processing-nlp-nltk.html','python-programming.html'),
('neo4j-graph-database-essential-training.html','graph-database-courses.html'),
('no-code-ai-agent-courses.html','ai-agents-series.html'),
('node-js-services-development-lfw212.html','linux-foundation-certification-exam-prep-courses.html'),
('node-js-training-courses.html','javascript-training-courses-in.html'),
('notion-essential-training.html','content-management-cms-skillsfuture-courses.html'),
('notion-masterclass-project-and-content-management-essentials.html','project-management-training-courses-in.html'),
('optimisation-statistical-decision-analysis.html','data-analytics-courses.html'),
('orange-courses.html','business-intelligence-software-courses.html'),
('pearson-vue-certified-it-specialist-computational-thinking.html','computer-programming-and-infocomm-courses.html'),
('pearson-vue-certified-it-specialist-cybersecurity.html','cybersecurity-threat-analysis-courses.html'),
('pearson-vue-certified-it-specialist-data-analytics.html','data-analytics-courses.html'),
('pearson-vue-certified-it-specialist-databases.html','relational-sql-databases.html'),
('pearson-vue-certified-it-specialist-device-configuration-and-management.html','linux-courses.html'),
('pearson-vue-certified-it-specialist-html-and-css.html','html-css-training-courses.html'),
('pearson-vue-certified-it-specialist-java.html','programming-courses.html'),
('pearson-vue-certified-it-specialist-javascript.html','javascript-training-courses-in.html'),
('pearson-vue-certified-it-specialist-network-security.html','network-securities-courses.html'),
('pearson-vue-certified-it-specialist-networking.html','networks-training-in.html'),
('pearson-vue-certified-it-specialist-python.html','python-programming.html'),
('pearson-vue-certified-it-specialist-software-development.html','computer-programming-and-infocomm-courses.html'),
('pearson-vue-it-specialist-exam-vouchers-1.html','certification-exam-prep-courses.html'),
('pearson-vue-it-specialist-exam-vouchers.html','certification-exam-prep-courses.html'),
('pearson-vue-it-specialists.html','certification-exam-prep-courses.html'),
('person-vue-it-specialist-exam-prep.html','certification-exam-prep-courses.html'),
('personal-and-corporate-tax-computation-and-compliance.html','accounting-courses.html'),
('personal-development-courses.html','business-soft-skills-courses.html'),
('pl-200-microsoft-power-platform-functional-consultant-exam-prep.html','power-automate-software-training.html'),
('pl-600-microsoft-power-platform-solution-architect-exam-prep.html','power-automate-software-training.html'),
('pl-7001-create-and-manage-canvas-apps-with-power-app.html','microsoft-power-apps-software-training.html'),
('pl-7004-implement-ai-models-with-microsoft-power-platform-ai-builder.html','microsoft-power-platform-software-training-courses.html'),
('pmp-itil-practice-exams.html','itil-4-certification-exam-prep-courses.html'),
('pmp-practice-exams.html','project-management-training-courses-in.html'),
('postman-essential-training.html','rest-api-courses.html'),
('power-platform-specialisation.html','power-automate-software-training.html'),
('powershell-for-beginners.html','linux-courses.html'),
('predictive-analytics-with-orange.html','data-management-courses.html'),
('problem-solving-creativity-for-kids.html','thinking-critically-critical-core-skills-courses.html'),
('procreate-digital-art-courses.html','digital-graphics-software-training.html'),
('professional-networking-and-lead-generation-on-linkedin.html','social-media-marketing-training-courses.html'),
('project-management-training-courses-in-singapore.html','project-management-training-courses-in.html'),
('pydantic-for-structured-data-validation-in-llm-workflows.html','computer-programming-and-infocomm-courses.html'),
('python-computer-science-tuition-singapore.html','python-programming.html'),
('python-flask-web-development-training.html','python-programming.html'),
('pytorch-machine-leanring-courses.html','ai-for-machine-learning.html'),
('qlik-sense-business-analytics-training.html','data-management-courses.html'),
('qlikviiew-qliksense-software-training-courses.html','business-intelligence-software-courses.html'),
('quickbooks-certified-user.html','quickbooks-training-courses.html'),
('r-programming-courses-in-1.html','r-programming-courses-in.html'),
('r-statistics-essential-training-in.html','r-programming-courses-in.html'),
('raspberry-pi-internet-of-things-iot.html','internet-of-things-iot-training-in.html'),
('raspberry-pi-robotics-workshop-for-kids.html','raspberry-pi-courses-in.html'),
('reducing-waste-and-improving-workplace-efficiency-with-lean-six-sigma.html','six-sigma-courses.html'),
('responsive-web-design-training-in-1.html','web-design-courses.html'),
('revit-for-architectural-design-autodesk-certified-professional-cert-prep.html','technical-drawing-courses.html'),
('revit-for-architectural-design-professional-certification-acp-prep.html','technical-drawing-courses.html'),
('revit-for-structural-design-professional-certification-acp-prep.html','technical-drawing-courses.html'),
('rhino-masterclass.html','3d-modeling-courses.html'),
('rhino-trainings.html','digital-graphics-software-training.html'),
('risc-v-foundational-associate-rvfa-prep.html','linux-foundation-certification-exam-prep-courses.html'),
('risc-v-fundamentals-lfd210.html','linux-foundation-certification-exam-prep-courses.html'),
('robot-operating-system-ros-specialization.html','robot-operating-system-ros-courses.html'),
('robotic-process-automation-with-uipath.html','rpa-api-it-automation-courses.html'),
('ros-for-beginners.html','robot-operating-system-ros-courses.html'),
('rpa-automation-anywhere-training.html','rpa-api-it-automation-courses.html'),
('rpa-courses.html','rpa-api-it-automation-courses.html'),
('safeguarding-against-online-and-phone-scams.html','cybersecurity-threat-analysis-courses.html'),
('sc-200-microsoft-security-operations-analyst-exam-prep.html','cybersecurity-threat-analysis-courses.html'),
('sc-300-microsoft-certified-identity-and-access-administrator-associate-exam-prep.html','cybersecurity-threat-analysis-courses.html'),
('sc-400-microsoft-certified-information-protection-and-compliance-administrator-associate-exam-prep.html','data-governance-protection-courses.html'),
('sc-5002-secure-azure-services-and-workloads-with-microsoft-defender-for-cloud-regulatory-compliance-controls.html','cybersecurity-threat-analysis-courses.html'),
('sc-5003-implement-information-protection-and-data-loss-prevention-by-using-microsoft-purview.html','cybersecurity-threat-analysis-courses.html'),
('sc-900-microsoft-security-compliance-and-identity-fundamentals-exam-prep.html','cybersecurity-threat-analysis-courses.html'),
('scikit-learn-machine-learning-courses.html','ai-for-machine-learning.html'),
('selenium-essential-training.html','rpa-api-it-automation-courses.html'),
('selenium-training.html','rpa-api-it-automation-courses.html'),
('self-paced-e-learning-coures/comptia-self-paced-e-learning-courses.html','comptia-certification-prep-courses.html'),
('seo-for-ecommerce.html','ecommerce-training-courses.html'),
('software-defined-networking-training.html','networks-training-in.html'),
('software-defined-networks-courses.html','networks-training-in.html'),
('software-training-courses/autodesk-software-courses/autodesk-maya-trainings.html','3d-modeling-courses.html'),
('software-training-courses/gaming-software-courses/unreal-engine-training-courses.html','gaming-animation-and-video-courses-in.html'),
('solving-problems-with-machine-learning.html','computer-programming-and-infocomm-courses.html'),
('statistical-data-analysis-training-with-excel-in.html','microsoft-excel-trainings.html'),
('supercharging-your-productivity-with-microsoft-365-copilot-pro.html','microsoft-365-copilot-masterclass.html'),
('sustainability-esg-carbon-management-wsq-courses.html','wsq-sustainability-esg-courses.html'),
('swift-programming-training-courses.html','programming-courses.html'),
('tableau-ad-neo4j-certification-courses.html','tableau-certification-exam-prep.html'),
('text-mining-with-orange.html','data-management-courses.html'),
('text-mining-with-r.html','r-programming-courses-in.html'),
('tiktok-social-media-courses.html','video-marketing-live-streaming-courses.html'),
('training-linux-system-administration-training-course-fundamentals-of-open-source-it-and-cloud-computing-lfs200.html','linux-courses.html'),
('unity-certification-exam-prep-courses-1.html','gaming-animation-and-video-courses-in.html'),
('unity-training-courses.html','gaming-animation-and-video-courses-in.html'),
('unity-unreal-certification-exam-prep-courses.html','gaming-animation-and-video-courses-in.html'),
('unix-and-bash-script-essential-training.html','linux-courses.html'),
('unleash-your-creativity-with-procreate-digital-arts.html','2d-design-courses.html'),
('unreal-engine-training-courses.html','gaming-animation-and-video-courses-in.html'),
('ux-ui-design-with-figma.html','ux-ui-design-courses.html'),
('verilog-programming-training-for-fpga.html','electronics-coures.html'),
('vhdl-programming-fpga-training.html','electronics-coures.html'),
('vibe-coding-for-algorithmic-trading-and-value-investment.html','algorithmic-trading-quantitative-analysis-courses.html'),
('vulnerability-management-with-nessus.html','cybersecurity-threat-analysis-courses.html'),
('web-framework-courses.html','web-design-courses.html'),
('wiley-certified-deep-learning-specialist-citrep.html','deep-learning-computer-vision-courses.html'),
('wordpress-ecommerce-and-woocommerce-training-courses-in-singapore.html','wordpress-ecommerce-and-woocommerce-training-courses-in.html'),
('wsh-workplace-safety-health-courses.html','healthcare-and-wsh-courses.html'),
('wsq-ai-genai-agentic-ai-courses.html','wsq-agentic-ai-courses.html'),
('wsq-cisco-certified-network-professional-ccnp-for-enarsi-training.html','networks-training-in.html'),
('wsq-content-creation-for-video-social-media-platforms.html','wsq-media-marketing-courses.html'),
('wsq-finance-mfg-green-courses-1.html','wsq-finance-mfg-green-courses.html'),
('wsq-iot-robotics-courses-1.html','wsq-iot-robotics-courses.html'),
('wsq-media-marketing-courses-1.html','wsq-media-marketing-courses.html'),
('xiaohongshu-for-business-boost-your-sales-with-social-commerce.html','social-media-marketing-training-courses.html');

UPDATE tmp_gsc404 SET k = LEFT(src, CHAR_LENGTH(src) - 5) WHERE src LIKE '%.html' AND src NOT LIKE '%/%';
DELETE FROM tmp_gsc404 WHERE @ok IS NULL OR @ok <> 1;

SET @pet := (SELECT entity_type_id FROM eav_entity_type WHERE entity_type_code = 'catalog_product');
SET @cet := (SELECT entity_type_id FROM eav_entity_type WHERE entity_type_code = 'catalog_category');
SET @p_uk := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = @pet AND attribute_code = 'url_key');
SET @p_up := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = @pet AND attribute_code = 'url_path');
SET @p_st := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = @pet AND attribute_code = 'status');
SET @c_uk := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = @cet AND attribute_code = 'url_key');
SET @c_up := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = @cet AND attribute_code = 'url_path');
SET @c_ac := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id = @cet AND attribute_code = 'is_active');

-- 1a. Disabled products (effective SG status = 2) that still own a dead slug.
DROP TEMPORARY TABLE IF EXISTS tmp_gsc404_p;
CREATE TEMPORARY TABLE tmp_gsc404_p (entity_id INT UNSIGNED PRIMARY KEY, k VARCHAR(255)) DEFAULT CHARSET=utf8;
INSERT IGNORE INTO tmp_gsc404_p (entity_id, k)
SELECT v.entity_id, t.k
  FROM tmp_gsc404 t
  JOIN catalog_product_entity_varchar v ON v.attribute_id = @p_uk AND v.value = t.k
 WHERE t.k <> ''
   AND COALESCE((SELECT s.value FROM catalog_product_entity_int s WHERE s.entity_id = v.entity_id AND s.attribute_id = @p_st AND s.store_id = 1),
                (SELECT s.value FROM catalog_product_entity_int s WHERE s.entity_id = v.entity_id AND s.attribute_id = @p_st AND s.store_id = 0)) = 2
   AND NOT EXISTS (SELECT 1 FROM catalog_product_entity_varchar x WHERE x.attribute_id = @p_uk AND x.value = CONCAT(t.k, '-retired'));

UPDATE catalog_product_entity_varchar v JOIN tmp_gsc404_p p ON p.entity_id = v.entity_id
   SET v.value = CONCAT(p.k, '-retired')
 WHERE v.attribute_id = @p_uk AND v.value = p.k;
UPDATE catalog_product_entity_varchar v JOIN tmp_gsc404_p p ON p.entity_id = v.entity_id
   SET v.value = CONCAT(p.k, '-retired.html')
 WHERE v.attribute_id = @p_up AND v.value = CONCAT(p.k, '.html');

-- 1b. Inactive categories (effective SG is_active = 0) that still own a dead slug.
DROP TEMPORARY TABLE IF EXISTS tmp_gsc404_c;
CREATE TEMPORARY TABLE tmp_gsc404_c (entity_id INT UNSIGNED PRIMARY KEY, k VARCHAR(255)) DEFAULT CHARSET=utf8;
INSERT IGNORE INTO tmp_gsc404_c (entity_id, k)
SELECT v.entity_id, t.k
  FROM tmp_gsc404 t
  JOIN catalog_category_entity_varchar v ON v.attribute_id = @c_uk AND v.value = t.k
 WHERE t.k <> ''
   AND COALESCE((SELECT a.value FROM catalog_category_entity_int a WHERE a.entity_id = v.entity_id AND a.attribute_id = @c_ac AND a.store_id = 1),
                (SELECT a.value FROM catalog_category_entity_int a WHERE a.entity_id = v.entity_id AND a.attribute_id = @c_ac AND a.store_id = 0)) = 0
   AND NOT EXISTS (SELECT 1 FROM catalog_category_entity_varchar x WHERE x.attribute_id = @c_uk AND x.value = CONCAT(t.k, '-retired'));

UPDATE catalog_category_entity_varchar v JOIN tmp_gsc404_c c ON c.entity_id = v.entity_id
   SET v.value = CONCAT(c.k, '-retired')
 WHERE v.attribute_id = @c_uk AND v.value = c.k;
UPDATE catalog_category_entity_varchar v JOIN tmp_gsc404_c c ON c.entity_id = v.entity_id
   SET v.value = CONCAT(c.k, '-retired.html')
 WHERE v.attribute_id = @c_up AND v.value = CONCAT(c.k, '.html');

-- 2. Replace whatever row sits on each dead slug with a manual 301.
DELETE r FROM core_url_rewrite r JOIN tmp_gsc404 t ON t.src = r.request_path
 WHERE r.store_id IN (0, 1) AND r.id_path NOT LIKE 'gsc404-%';

INSERT INTO core_url_rewrite (store_id, id_path, request_path, target_path, is_system, options)
SELECT 0, CONCAT('gsc404-', MD5(t.src)), t.src, t.dst, 0, 'RP' FROM tmp_gsc404 t
 WHERE NOT EXISTS (SELECT 1 FROM core_url_rewrite x WHERE x.request_path = t.src AND x.store_id = 0);
INSERT INTO core_url_rewrite (store_id, id_path, request_path, target_path, is_system, options)
SELECT 1, CONCAT('gsc404-', MD5(t.src)), t.src, t.dst, 0, 'RP' FROM tmp_gsc404 t
 WHERE NOT EXISTS (SELECT 1 FROM core_url_rewrite x WHERE x.request_path = t.src AND x.store_id = 1);

UPDATE core_url_rewrite r JOIN tmp_gsc404 t ON t.src = r.request_path
   SET r.target_path = t.dst, r.options = 'RP'
 WHERE r.store_id IN (0, 1) AND r.id_path LIKE 'gsc404-%' AND r.target_path <> t.dst;

-- 3. Flatten chains: redirects and search terms that pointed at a dead slug.
UPDATE core_url_rewrite r JOIN tmp_gsc404 t ON r.target_path IN (t.src, CONCAT('https://www.tertiarycourses.com.sg/', t.src))
   SET r.target_path = t.dst
 WHERE r.store_id IN (0, 1) AND r.options IN ('R', 'RP') AND r.request_path <> t.dst;

UPDATE catalogsearch_query q JOIN tmp_gsc404 t ON q.redirect = CONCAT('https://www.tertiarycourses.com.sg/', t.src)
   SET q.redirect = CONCAT('https://www.tertiarycourses.com.sg/', t.dst)
 WHERE q.store_id = 1;

DROP TEMPORARY TABLE IF EXISTS tmp_gsc404_p;
DROP TEMPORARY TABLE IF EXISTS tmp_gsc404_c;
DROP TEMPORARY TABLE IF EXISTS tmp_gsc404;
