-- 232: Make the "Regional Franchisee" menu item link to /franchising-application.html.
--
-- The menu is category-driven, so the link is the category's own URL. Change
-- category 180's url_key from regional-franchising-application to
-- franchising-application — the menu URL becomes /franchising-application.html.
-- The category already renders the franchise landing block (migration 230, static
-- block display), so that URL serves the same content. No collision: no other
-- category uses this url_key and the CMS page only resolved via the CMS router
-- fallback (now shadowed by the category rewrite, identical content either way).
--
-- The url_rewrite + url_path are regenerated by the catalog_url reindex, which the
-- deploy entrypoint already runs on every boot.

UPDATE catalog_category_entity_varchar v JOIN eav_attribute ea ON ea.attribute_id = v.attribute_id AND ea.attribute_code = 'url_key' AND ea.entity_type_id = 3 SET v.value = 'franchising-application' WHERE v.entity_id = 180 AND v.value = 'regional-franchising-application';

DELETE v FROM catalog_category_entity_varchar v JOIN eav_attribute ea ON ea.attribute_id = v.attribute_id AND ea.attribute_code = 'url_path' AND ea.entity_type_id = 3 WHERE v.entity_id = 180;
