-- Repurpose C505 "eLearning Instructional Design" -> "Generative AI for
-- Curriculum Development".
--
--   url_key: elearning-instructional-design -> generative-ai-for-curriculum-development
--
-- Rebrand + overview rewrite: name, url_key, short_description, meta_*, image
-- labels, and the media-gallery per-image label. The curriculum
-- (description), price and duration are intentionally KEPT — rewriting the
-- syllabus is a separate content task.
--
-- Categories are NOT changed. C505 sits in Instructional Design (13),
-- eLearning (299), eLearning Content Creation (377), Media & Design (69) and
-- Adult Courses (3). Curriculum development remains a legitimate fit for all
-- of them under the new title, and the user did not request a move.
--
-- The 301 from the old slug is NOT written here — core_url_rewrite must be
-- regenerated by the catalog_url reindex FIRST, otherwise the reindex
-- clobbers/re-points the row. See migration 603.
-- (memory: catalog_url reindex regenerates disabled-category 301 -> 404)
--
-- Includes the media-gallery label UPDATE that the 595 template omits — the
-- product-page zoom gallery renders that label as the img title/alt, so the
-- old course name leaks there otherwise.
-- (memory: feedback_course_repurpose_cross_site_rollout addendum 5, C597 run)
--
-- Clears per-store overrides of the rewritten attributes so partner store
-- scopes can't shadow store 0, and drops url_path at every scope (C505 has a
-- live store-1 url_path row holding the OLD slug — it would shadow the new
-- URL). Guarded with @e505 IS NOT NULL so it is a no-op on sites without this
-- SKU. Store scope 0. Idempotent. No content line ends in a semicolon.

SET @e505 := (SELECT entity_id FROM catalog_product_entity WHERE sku='C505');

SET @a_name  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='name');
SET @a_uk    := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='url_key');
SET @a_short := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='short_description');
SET @a_mt    := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='meta_title');
SET @a_md    := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='meta_description');
SET @a_mk    := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='meta_keyword');
SET @a_il    := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='image_label');
SET @a_sil   := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='small_image_label');
SET @a_til   := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=4 AND attribute_code='thumbnail_label');

-- ---------------------------------------------------------------------------
-- C505 -> Generative AI for Curriculum Development
-- ---------------------------------------------------------------------------

INSERT INTO catalog_product_entity_varchar (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_name, 0, @e505, 'Generative AI for Curriculum Development' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_product_entity_varchar (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_uk, 0, @e505, 'generative-ai-for-curriculum-development' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_short, 0, @e505, '<p>Discover how generative AI is reshaping the way courses and training programmes are designed with our Generative AI for Curriculum Development course. Designed for trainers, instructional designers, educators and L&amp;D professionals, this course shows you how to use AI tools to accelerate every stage of curriculum design — from learning-needs analysis and learning outcomes to lesson structure, content drafting and assessment design. You will learn how to write effective prompts that produce usable instructional material rather than generic filler.</p>
<p>Beyond the tools, this course focuses on judgement: how to evaluate AI-generated content for accuracy, alignment to learning outcomes and appropriateness for your learners, and where the designer''s expertise must stay firmly in the loop. Through hands-on practice you will build a working curriculum blueprint with AI assistance, and leave with a repeatable workflow you can apply to your own courses immediately.</p>' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_product_entity_varchar (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_mt, 0, @e505, 'Generative AI for Curriculum Development | Tertiary Courses Singapore' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_md, 0, @e505, 'Learn to design courses with generative AI — AI-assisted learning-needs analysis, learning outcomes, lesson structure, content drafting and assessment design for trainers and instructional designers in Singapore.' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_product_entity_text (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_mk, 0, @e505, 'Generative AI for Curriculum Development, AI curriculum design, AI instructional design, AI lesson planning, AI course design, prompt engineering for trainers, learning outcomes, assessment design, instructional design, Singapore' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_product_entity_varchar (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_il, 0, @e505, 'Generative AI for Curriculum Development' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO catalog_product_entity_varchar (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_sil, 0, @e505, 'Generative AI for Curriculum Development' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);
INSERT INTO catalog_product_entity_varchar (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 4, @a_til, 0, @e505, 'Generative AI for Curriculum Development' FROM DUAL WHERE @e505 IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

-- Media-gallery per-image label (rendered as the zoom img title/alt).
UPDATE catalog_product_entity_media_gallery_value gv
JOIN catalog_product_entity_media_gallery g ON g.value_id = gv.value_id
SET gv.label = 'Generative AI for Curriculum Development'
WHERE g.entity_id = @e505 AND @e505 IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Clear per-store overrides so partner store scopes can't shadow store 0.
-- ---------------------------------------------------------------------------

DELETE v FROM catalog_product_entity_varchar v
WHERE v.entity_id = @e505 AND v.store_id <> 0 AND @e505 IS NOT NULL
  AND v.attribute_id IN (@a_name, @a_uk, @a_mt, @a_il, @a_sil, @a_til);

DELETE v FROM catalog_product_entity_text v
WHERE v.entity_id = @e505 AND v.store_id <> 0 AND @e505 IS NOT NULL
  AND v.attribute_id IN (@a_short, @a_md, @a_mk);

-- Drop stale url_path rows at EVERY scope so the catalog_url reindex rebuilds
-- them from the new url_key rather than reusing the old slug. C505 has a live
-- store-1 row holding 'elearning-instructional-design.html'.
DELETE v FROM catalog_product_entity_varchar v
JOIN eav_attribute a ON a.attribute_id = v.attribute_id AND a.entity_type_id = 4 AND a.attribute_code = 'url_path'
WHERE v.entity_id = @e505 AND @e505 IS NOT NULL;
