-- Flatten the "eLearning" sub-tree into "Instructional Design" and retire the
-- eLearning containers.
--
--   Media & Design (69)
--   +- Instructional Design (13)          <- SURVIVES, receives everything
--   +- eLearning (299)                    <- products moved out, DISABLED
--      +- eLearning Content Creation (377) <- products moved out, DISABLED
--      +- Learning Management System (378) <- already disabled, products moved
--
-- Every product under 299/377/378 is added to 13, then the three eLearning
-- category memberships are dropped and 299 + 377 are disabled. 378 is already
-- is_active=0 but still holds 3 products, so it is drained too — otherwise
-- those courses would lose their last Media & Design home.
--
-- 377's product set is a strict SUBSET of 299's, so the union is what matters,
-- not the per-category lists. Products already in 13 (C505, M478,
-- TGS-2024051519) are handled by INSERT ... ON DUPLICATE KEY so no duplicates.
--
-- Disabled products (C902, C1059, C906) are moved too — they keep their
-- category membership so that re-enabling one later still lands it somewhere
-- sensible. Membership of a disabled product is invisible on the storefront.
--
-- Position: appended after 13's current max so existing ordering is preserved.
-- The category-ordering pass (WSQ first, then non-WSQ alphabetical) renumbers
-- properly afterwards and should be run on 13 after this.
--
-- The 301s for the retired category URLs are NOT written here — core_url_rewrite
-- must be regenerated by the catalog_url reindex FIRST, otherwise the reindex
-- re-points them at catalog/category/view/id/<id>, which 301s into a 404.
-- See migration 606. (memory: catalog_url reindex regenerates disabled-category
-- 301 -> 404; and migration 588's order-of-operations note)
--
-- Categories resolved BY NAME + parent so this is a no-op on partner sites
-- whose category ids differ. (memory: category ids DIFFER per site)
-- Store scope 0. Idempotent. No content line ends in a semicolon.

SET @a_cname := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=3 AND attribute_code='name');
SET @a_cact  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=3 AND attribute_code='is_active');

-- Media & Design (level-3 container under Adult Courses).
SET @md := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='Media & Design' AND e.level=3 LIMIT 1) r);

SET @id13 := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='Instructional Design' AND e.parent_id=@md LIMIT 1) r);

SET @el := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='eLearning' AND e.parent_id=@md LIMIT 1) r);

SET @elcc := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='eLearning Content Creation' AND e.parent_id=@el LIMIT 1) r);

SET @lms := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='Learning Management System (LMS)' AND e.parent_id=@el LIMIT 1) r);

-- Only proceed when the surviving target and the source parent both resolve.
SET @ok := (@id13 IS NOT NULL AND @el IS NOT NULL);

SET @base := (SELECT COALESCE(MAX(position),0) FROM catalog_category_product WHERE category_id=@id13);

-- ---------------------------------------------------------------------------
-- 1. Move every product from the eLearning sub-tree into Instructional Design.
-- ---------------------------------------------------------------------------

-- MySQL 5.7: no ROW_NUMBER() window function — use a session counter.
SET @rn := @base;

INSERT INTO catalog_category_product (category_id, product_id, position)
SELECT @id13, s.product_id, @rn := @rn + 1
FROM (SELECT DISTINCT cp.product_id FROM catalog_category_product cp
      WHERE cp.category_id IN (@el, @elcc, @lms)
        AND NOT EXISTS (SELECT 1 FROM catalog_category_product x
                        WHERE x.category_id=@id13 AND x.product_id=cp.product_id)
      ORDER BY cp.product_id) s
WHERE @ok
ON DUPLICATE KEY UPDATE position = catalog_category_product.position;

-- ---------------------------------------------------------------------------
-- 2. Drop the now-redundant eLearning memberships.
-- ---------------------------------------------------------------------------

DELETE FROM catalog_category_product
WHERE @ok AND category_id IN (@el, @elcc, @lms);

-- ---------------------------------------------------------------------------
-- 3. Disable the drained eLearning containers (377 first, then 299).
--    378 is already disabled; set it anyway so the state is explicit.
-- ---------------------------------------------------------------------------

INSERT INTO catalog_category_entity_int (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 3, @a_cact, 0, c.id, 0 FROM (
  SELECT @el AS id UNION ALL SELECT @elcc UNION ALL SELECT @lms
) c
WHERE @ok AND c.id IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

-- Clear per-store is_active overrides so a store scope can't keep them visible.
DELETE i FROM catalog_category_entity_int i
WHERE @ok AND i.attribute_id=@a_cact AND i.store_id<>0
  AND i.entity_id IN (@el, @elcc, @lms);

-- Hide them from the mega-menu as well (include_in_menu), belt-and-braces:
-- a disabled category should never render as a nav item.
SET @a_menu := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=3 AND attribute_code='include_in_menu');

INSERT INTO catalog_category_entity_int (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 3, @a_menu, 0, c.id, 0 FROM (
  SELECT @el AS id UNION ALL SELECT @elcc UNION ALL SELECT @lms
) c
WHERE @ok AND @a_menu IS NOT NULL AND c.id IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

DELETE i FROM catalog_category_entity_int i
WHERE @ok AND i.attribute_id=@a_menu AND i.store_id<>0
  AND i.entity_id IN (@el, @elcc, @lms);
