-- Flatten "Game Development" into its parent "Gaming & Animation" and retire
-- the now-empty sub-category.
--
--   Media & Design (69)
--   +- Gaming & Animation (100)      <- SURVIVES, receives everything
--      +- Game Development (128)     <- products moved out, DISABLED
--
-- 128 has no child categories and all 10 of its products are ALREADY members
-- of the parent 100, so the "move" is a no-op in practice — the INSERT below
-- is kept anyway so the migration is correct on any site where that overlap
-- is not total (partner catalogs were imported independently).
--
-- All 10 products are enabled, incl. 3 WSQ (TGS-) courses. None of them loses
-- a home: they remain in Gaming & Animation.
--
-- Mirrors the eLearning flatten in migration 605 and the Soft Skills flatten
-- in 586/588. The 301 for the retired category URL is NOT written here —
-- core_url_rewrite must be regenerated by the catalog_url reindex FIRST,
-- otherwise the reindex re-points it at catalog/category/view/id/<id>, which
-- 301s into a 404. See migration 608.
--
-- NOTE: the surviving url_key for 128 is 'game-devleopment-courses-in' — the
-- typo ("devleopment") is in the LIVE data and is reproduced deliberately in
-- the 301 source path. Do not "fix" it here; the indexed URL is the typo'd one.
--
-- Categories resolved BY NAME + parent so this is a no-op on partner sites
-- whose category ids differ. Store scope 0. Idempotent.

SET @a_cname := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=3 AND attribute_code='name');
SET @a_cact  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=3 AND attribute_code='is_active');
SET @a_menu  := (SELECT attribute_id FROM eav_attribute WHERE entity_type_id=3 AND attribute_code='include_in_menu');

SET @md := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='Media & Design' AND e.level=3 LIMIT 1) r);

SET @ga := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='Gaming & Animation' AND e.parent_id=@md LIMIT 1) r);

SET @gd := (SELECT entity_id FROM (SELECT e.entity_id FROM catalog_category_entity e
  JOIN catalog_category_entity_varchar v ON v.entity_id=e.entity_id AND v.attribute_id=@a_cname AND v.store_id=0
  WHERE TRIM(v.value)='Game Development' AND e.parent_id=@ga LIMIT 1) r);

SET @ok := (@ga IS NOT NULL AND @gd IS NOT NULL);

SET @base := (SELECT COALESCE(MAX(position),0) FROM catalog_category_product WHERE category_id=@ga);

-- 1. Move any product not already in the parent.
-- MySQL 5.7: no ROW_NUMBER() window function — use a session counter.
SET @rn := @base;

INSERT INTO catalog_category_product (category_id, product_id, position)
SELECT @ga, s.product_id, @rn := @rn + 1
FROM (SELECT DISTINCT cp.product_id FROM catalog_category_product cp
      WHERE cp.category_id = @gd
        AND NOT EXISTS (SELECT 1 FROM catalog_category_product x
                        WHERE x.category_id=@ga AND x.product_id=cp.product_id)
      ORDER BY cp.product_id) s
WHERE @ok
ON DUPLICATE KEY UPDATE position = catalog_category_product.position;

-- 2. Drop the Game Development memberships.
DELETE FROM catalog_category_product WHERE @ok AND category_id = @gd;

-- 3. Disable + unlist the drained container.
INSERT INTO catalog_category_entity_int (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 3, @a_cact, 0, @gd, 0 FROM DUAL WHERE @ok
ON DUPLICATE KEY UPDATE value = VALUES(value);

INSERT INTO catalog_category_entity_int (entity_type_id, attribute_id, store_id, entity_id, value)
SELECT 3, @a_menu, 0, @gd, 0 FROM DUAL WHERE @ok AND @a_menu IS NOT NULL
ON DUPLICATE KEY UPDATE value = VALUES(value);

-- Clear per-store overrides so a store scope can't keep it visible.
DELETE i FROM catalog_category_entity_int i
WHERE @ok AND i.store_id<>0 AND i.entity_id=@gd
  AND i.attribute_id IN (@a_cact, @a_menu);
