-- 631: redirect common MISSPELLINGS of the AI series terms to the right page.
--
-- WHY: the user searched "ai applicatoins" (transposed 'oi') and got no redirect --
-- 630's hand-listed typos covered 'aplications' and 'applicaton' but not that one.
-- Hand-guessing typos one at a time does not converge, so these are GENERATED:
-- for each routed phrase, every word of 4+ chars is expanded by single-character
-- transposition, deletion and doubling. 'ai' / 'gen' are left alone (too short to
-- mangle safely).
--
-- SAFETY: checked against production before shipping -- every generated variant that
-- already existed in catalogsearch_query was either unsearched or already pointing at
-- the SAME target, so no real course search is shadowed by a typo. Variants that
-- collide with a phrase we already route are dropped.
--
-- Fills EMPTY redirects only and seeds unsearched variants with display_in_terms = 0
-- so the public search-terms page is not polluted.
-- Partner-safe: guard matches the SG store by its store code, so MY/GH are a no-op.

SET @sg := (SELECT COUNT(*) FROM core_store WHERE store_id = 1 AND code = 'singapore');

DROP TEMPORARY TABLE IF EXISTS tmp_typo_map;
CREATE TEMPORARY TABLE tmp_typo_map (
  code   VARCHAR(128) NOT NULL PRIMARY KEY,
  target VARCHAR(255) NOT NULL
) ENGINE=MEMORY;

INSERT INTO tmp_typo_map (code, target) VALUES
  ('aagentic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aagentic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aegntic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aegntic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aentic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aentic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ageentic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ageentic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenitc','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenitc ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenntic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenntic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agentc','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agentc ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agentci','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agentci ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenti','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenti ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenticc','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenticc ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agentiic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agentiic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenttic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agenttic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agetic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agetic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agetnic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agetnic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aggentic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('aggentic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agnetic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agnetic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agntic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('agntic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aagent','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aagents','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aapplication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai aapplications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai aapps','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai aegnt','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aegnts','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aent','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aents','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai ageent','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai ageents','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agen','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agennt','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agennts','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agens','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agenst','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agentss','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agentt','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agentts','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aget','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agetn','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agetns','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agets','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aggent','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aggents','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agnet','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agnets','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agnt','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai agnts','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai aplication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai aplications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai aplpication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai aplpications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appilcation','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appilcations','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applcation','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applcations','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applciation','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applciations','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliaction','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliactions','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliation','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliations','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaation','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaations','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaion','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaions','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaiton','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaitons','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatiion','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatiions','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatin','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatino','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatinos','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatins','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatio','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicationn','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicationns','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicationss','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatioon','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatioons','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatios','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatiosn','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatoin','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatoins','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicaton','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicatons','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicattion','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applicattions','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliccation','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliccations','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applictaion','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applictaions','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliction','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai applictions','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appliications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appllication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appllications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appplication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appplications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appps','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai appss','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai apsp','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai cber security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cbyer security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai ccyber security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cybber security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cybe security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cybeer security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber ecurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber escurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber sceurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber scurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber seccurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber secrity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber secruity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber secuirty','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber secuity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securiity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securit','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securitty','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securityy','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securiy','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securiyt','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securrity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securtiy','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber securty','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber secuurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber seecurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber seucrity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber seurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyber ssecurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyberr security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cybr security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cybre security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyebr security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyer security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai cyyber security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai ddevops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai deevops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai deops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai deovps','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devoops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devop','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devopps','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devopss','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devos','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devosp','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devpos','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devps','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai devvops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai dveops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai dvops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai ecurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai edvops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai escurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai evops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ai gaent','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai gaents','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai gent','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai gents','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ai paplication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai paplications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai paps','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai pplication','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai pplications','https://www.tertiarycourses.com.sg/ai-applications-series.html'),
  ('ai sceurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai scurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai seccurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai secrity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai secruity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai secuirty','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai secuity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securiity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securit','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securitty','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securityy','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securiy','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securiyt','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securrity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securtiy','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai securty','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai secuurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai seecurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai seucrity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai seurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai ssecurity','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai yber security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('ai ycber security','https://www.tertiarycourses.com.sg/ai-security-series.html'),
  ('calude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('calude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('calude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('caude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('caude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('caude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cclaude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cclaude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cclaude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('ccodex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('ccodex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('cdex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('cdex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('cdoex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('cdoex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('claaude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claaude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claaude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clade','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clade ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clade code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cladue','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cladue ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cladue code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claud','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claud ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claud code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claudde','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claudde ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claudde code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude ccode','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude cdoe','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude codde','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude codee','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude coed','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude coode','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claude ocde','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claudee','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claudee ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claudee code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claue','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claue ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claue code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claued','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claued ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('claued code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clauude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clauude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clauude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cllaude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cllaude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cllaude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cluade','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cluade ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('cluade code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('clude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('coddex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coddex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('code','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('code ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codeex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codeex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codexx','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codexx ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codx','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codx ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codxe','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('codxe ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coedx','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coedx ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coodex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('coodex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('egnai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('egnerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('enai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('enerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gaentic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('gaentic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('geai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geani','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geenai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geenerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geenrative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gena','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genaai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genaii','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geneartive ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geneative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geneerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generaative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generaitve ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generaive ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generatie ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generatiev ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generatiive ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generativ ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generativee ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generativve ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generattive ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generatve ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generatvie ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('generrative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genertaive ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genertive ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('geni','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genia','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gennai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gennerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genrative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('genreative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gentic','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('gentic ai','https://www.tertiarycourses.com.sg/ai-agents-series.html'),
  ('ggenai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('ggenerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gnai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gneai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gneerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('gnerative ai','https://www.tertiarycourses.com.sg/generative-ai-series.html'),
  ('laude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('laude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('laude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('lcaude','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('lcaude ai','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('lcaude code','https://www.tertiarycourses.com.sg/claude-ai-series.html'),
  ('lmops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('lops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mllops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mloops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlop','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlopps','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlopss','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlos','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlosp','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlpos','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mlps','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mmlops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('molps','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('mops','https://www.tertiarycourses.com.sg/ai-devops-series.html'),
  ('ocdex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('ocdex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('odex','https://www.tertiarycourses.com.sg/codex-ai-series.html'),
  ('odex ai','https://www.tertiarycourses.com.sg/codex-ai-series.html')
;

UPDATE catalogsearch_query q
  JOIN tmp_typo_map m ON m.code = LOWER(TRIM(q.query_text))
SET q.redirect = m.target
WHERE @sg = 1 AND q.store_id = 1 AND (q.redirect IS NULL OR q.redirect = '');

INSERT INTO catalogsearch_query
  (query_text, store_id, num_results, popularity, redirect, display_in_terms, is_active, is_processed)
SELECT m.code, 1, 0, 0, m.target, 0, 1, 0
FROM tmp_typo_map m
WHERE @sg = 1
  AND NOT EXISTS (
    SELECT 1 FROM (SELECT LOWER(TRIM(query_text)) qt FROM catalogsearch_query WHERE store_id = 1) e
    WHERE e.qt = m.code
  );

DROP TEMPORARY TABLE IF EXISTS tmp_typo_map;
