<div class="page-title">
    <h1><?php echo Mage::helper('bankpayment')->__('Confirm Order') ?></h1>
</div>
<p>Your Order Confirmation was submitted and will be responded to as soon as possible. Thank you for buying</p>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>