<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<style>
.product-shop .sku span { font-size: 2em; line-height: 1.25em; font-family: "Oswald", georgia, serif;}
.product-view .product-shop .sku .label { font-weight: normal;}
.catalog-product-view .product-view .product-type-data > .price-box {   
    margin: 5px 0 0;
    padding: 5px 0;
}
.catalog-product-view .product-secondary-column h2 { line-height: 0.6em; }
.catalog-product-view .product-secondary-column p { line-height: 1.1em; font-size:16px;}
    
.product-view  ul.ammo li {
    padding-left: 25px!important;
    margin-left: 15px!important;
    }
.product-view  ammo.ul {
    list-style: none outside none;
}
    .short-description .std table {
    font-family: Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
    margin: 20px 0;
    font-size: 13px;background-color: #f2f2f2;
}
    .short-description .std table td, .short-description .std table th {
    border: 2px solid #000;
    padding: 8px;
}
.short-description .std table tr:nth-child(even){background-color: #f2f2f2;}

.short-description .std table tr:hover {background-color: #f2f2f2;}

.short-description .std table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #f2f2f2;

}
.product-view .box-tabs .std ul {
    margin-left: 2em;
}
.container2-wrapper .product-options p.required {
    top: 0;
	position: relative;
   

}
</style>
<?php
	$_helper = $this->helper('catalog/output');
	$_product = $this->getProduct();
    $_storeId = $_product->getStoreId();
	$productType = $_product->getTypeId(); 
	$theme = $this->helper('ultimo');
	$helperThis = $this->helper('ultimo/template_catalog_product_view');
	$helperSnippets = $this->helper('ultimo/rsnippets');
    $attributeSetId = $_product->getAttributeSetId();

	//CSS classes based on product type
	$productTypeId = $_product->getTypeId();
	$productTypeClasses = '';
	if ($productTypeId === 'grouped') {
		$productTypeClasses .= ' is-type-grouped';
	}

	//
	$shortDescription = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');

	//Rich snippets
	$useRichSnippets = ($helperSnippets->isEnabledOnProductPage() && $productTypeId !== 'grouped');
	$priceProperties = '';
	if ($useRichSnippets)
	{
		$priceProperties = $helperSnippets->getPriceProperties($_product); //Has to be called before getOfferItemscope
	}

	//Get grid classes for product page sections
	$grid = $helperThis->getGridClasses();

	//Product collaterals
	//--------------------------------------------------------------
	$section = array();
	$relatedProductsHtml = '';
	$upsellProductsHtml = '';
	
	//Related products.
	//If related products not assigned to collateral data container.
	if (!$theme->getCfg('product_page/collateral_related'))
	{
		$replaceRelated = $theme->getCfg('product_page/replace_related');
		if ($replaceRelated == 1) //don't replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
				$relatedProductsHtml = $tmpHtml;
			//$relatedProductsHtml = trim($this->getChildHtml('related_products_wrapper'));
		}
		elseif ($replaceRelated == 2) //if related is empty, replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('related_products_wrapper')))
				$relatedProductsHtml = $tmpHtml;
			else //related empty
				if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
					$relatedProductsHtml = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
		}
		elseif ($replaceRelated == 3) //replace with static block
		{
			if ($tmpHtml = $this->getChildHtml('block_product_replace_related'))
				$relatedProductsHtml = '<div class="block_product_replace_related">'. $tmpHtml .'</div>';
		}
	}

	//Up-sell products.
	//If up-sell products not assigned to collateral data container.
	if (!$theme->getCfg('product_page/collateral_upsell'))
	{
		$replaceUpsell = $theme->getCfg('product_page/replace_upsell');
		if ($replaceUpsell == 1) //don't replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
				$upsellProductsHtml = $tmpHtml;
			//$upsellProductsHtml = $this->getChildHtml('upsell_products_wrapper');
		}
		elseif ($replaceUpsell == 2) //if upsell is empty, replace with static block
		{
			if ($tmpHtml = trim($this->getChildHtml('upsell_products_wrapper')))
				$upsellProductsHtml = $tmpHtml;
			else //upsell empty
				if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
					$upsellProductsHtml = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
		}
		elseif ($replaceUpsell == 3) //replace with static block
		{
			if ($tmpHtml = $this->getChildHtml('block_product_replace_upsell'))
				$upsellProductsHtml = '<div class="block_product_replace_upsell">'. $tmpHtml .'</div>';
		}
	}

	//Assign blocks to selected position
	$p = array();

	//Related products
	$position = $theme->getCfg('product_page/related_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $relatedProductsHtml;
	else
		$p[$position] = $relatedProductsHtml;

	//Up-sell products
	$position = $theme->getCfg('product_page/upsell_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $upsellProductsHtml;
	else
		$p[$position] = $upsellProductsHtml;

	//Product collateral data (displayed as tabs or stacked blocks)
	$position = $theme->getCfg('product_page/collateral_position');
	if (isset($p[$position]))
		$p[$position] = $p[$position] . $this->getChildHtml('productCollaterals');
	else
		$p[$position] = $this->getChildHtml('productCollaterals');
?>

<script type="text/javascript">
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<input type="hidden" id="simpleProdPrice" name="simpleProdPrice" value="<?php echo $_product->getFinalPrice() ?>"/>
<input type="hidden" id="gstProdPrice" name="gstProdPrice" value="<?php echo $_product->getFinalPrice()+ ($_product->getFinalPrice()* 0.09) ?>"/>


<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view nested-container" <?php if ($useRichSnippets) echo $helperSnippets->getProductItemscope(); ?>>

	<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="no-display">
			<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
			<input type="hidden" name="related_product" id="related-products-field" value="" />
		</div>

		<div class="product-img-column <?php echo $grid['imgCol']; ?>">

			<?php echo $this->getChildHtml('media') ?>
			<?php echo $this->helper('ultimo/labels')->getLabels($_product); //Product labels ?>
			<?php echo $this->getChildHtml('container_product_image_1'); ?>
       <?php /*     
               <!-- Social bookmarks from http://www.addthis.com/get/sharing  -->
               
               
<!-- AddThis Button BEGIN -->
<div class="feature-wrapper top-border margin-bottom">
	<div class="addthis_toolbox addthis_default_style ">
	<a class="addthis_button_preferred_1"></a>
	<a class="addthis_button_preferred_2"></a>
	<a class="addthis_button_preferred_3"></a>
	<a class="addthis_button_preferred_4"></a>
	<a class="addthis_button_compact"></a>
	<a class="addthis_counter addthis_bubble_style"></a>
	</div>
	<script type="text/javascript" src="https://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-5054e6c6502d114f"></script>
</div>
<!-- AddThis Button END -->
*/ ?>
		</div>
		
		<div class="product-primary-column product-shop <?php echo $grid['primCol']; ?>">

			<div class="product-name">
				<h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
			</div>
			
			<?php echo $this->getReviewsSummaryHtml($_product, false, true); //reviews ?>

			<?php if ($shortDescription): ?>
				<div class="short-description"><div class="std" itemprop="description"><?php echo $shortDescription; ?></div></div>
			<?php endif;?>

			<?php echo $this->getChildHtml('container_product_primary_1'); ?>

			<?php if (isset($p['primCol_1'])) echo $p['primCol_1']; ?>

			<?php if ($sku = $_product->getSku()): ?>
				<?php //if ($theme->getCfg('product_page/sku')): ?>
					<div class="sku">
						<span class="label"><?php echo $this->__('Course Code'); ?>: </span>
						<span class="value"><?php echo $sku; ?></span>
					</div>
				<?php //endif; ?>
				<?php if ($useRichSnippets): ?><meta itemprop="productID" content="sku:<?php echo $sku; ?>" /><?php endif; ?>
			<?php endif; ?>

			<?php echo $this->getChildHtml('alert_urls'); //alerts ?>
			
			<?php /*?><?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments ?>
				<div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
			<?php endif; ?>

			<div <?php if ($useRichSnippets) echo $helperSnippets->getOfferItemscope(); ?>>
				<div class="product-type-data<?php echo $productTypeClasses; ?>"><?php echo $this->getChildHtml('product_type_data'); ?></div>
				<?php echo $this->getTierPriceHtml(); ?>
				<?php echo $priceProperties; ?>
			</div> <?php //end: offers ?>

			<?php if (!$this->hasOptions()): //add to cart when no options (e.g. simple products) ?>
				<?php if($_product->isSaleable()): ?>
					<div class="add-to-box">
						<?php echo $this->getChildHtml('addtocart') ?>
					</div>
				<?php endif; ?>
				<?php echo $this->getChildHtml('extra_buttons') ?>
			<?php endif; ?>

			<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
				<?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
					<div class="container1-wrapper"><?php echo $container1_html; ?></div>
				<?php endif; ?>
			<?php endif;?>
			
			<?php if ($addtoLinksHtml = $this->getChildHtml('addto')): //compare, wishlist, send to friend ?>
				<div class="action-box clearer">
					<?php echo $addtoLinksHtml; ?>
				</div>
			<?php endif; ?>

			<?php if (isset($p['primCol_2'])) echo $p['primCol_2']; ?>

			<?php echo $this->getChildHtml('other'); ?>

			<?php echo $this->getChildHtml('container_product_primary_2'); ?><?php */?>

		</div> <!-- end: product-shop -->
		
		<?php if (isset($grid['secCol'])): //(!empty($secondaryColUnits)): ?>

			<div class="product-secondary-column <?php echo $grid['secCol']; ?> custom-sidebar-right">
				<div class="inner">
				<?php if($productType=="simple") { echo '<h2>Price</h2>'; } elseif($productType=="virtual") { 
    
    echo '<h2>Fee</h2>'; 


} else { echo '<h2>Information</h2>' ;  } ?>

<?php if ($extrahint_html = $this->getChildHtml('extrahint')): //qty increments ?>
				<div class="extrahint-wrapper"><?php echo $extrahint_html; ?></div>
			<?php endif; ?>

			<div <?php if ($useRichSnippets) echo $helperSnippets->getOfferItemscope(); ?>>
				<div id="productTypeData" class="product-type-data<?php echo $productTypeClasses; ?>"><?php echo $this->getChildHtml('product_type_data'); ?></div>
				<?php echo $this->getTierPriceHtml(); ?>
				<?php echo $priceProperties; ?>
			</div> <?php //end: offers ?>

			<?php 
			  if(($_storeId==1 || $_storeId==7) && $attributeSetId==4) 
			  { 
				echo '<p style="color:#ee001c;line-height: 1.3;clear:both;">The course fee listed above is before subsidy/grant, if applicable. We will apply for the grant and send you the invoice with nett fee.</p>' ;  
			  }
			  ?>

			<?php if (!$this->hasOptions()): //add to cart when no options (e.g. simple products) ?>
				<?php if($_product->isSaleable()): ?>
					<div class="add-to-box">
						<?php echo $this->getChildHtml('addtocart') ?>
					</div>
				<?php endif; ?>
				<?php echo $this->getChildHtml('extra_buttons') ?>
			<?php endif; ?>

			<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
				<?php if ($container1_html = $this->getChildChildHtml('container1', '', true, true)): ?>
					<div class="container1-wrapper"><?php echo $container1_html; ?></div>
				<?php endif; ?>
			<?php endif;?>


					<?php if ($_product->isSaleable() && $this->hasOptions()): ?>
					<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
                        <div class="box-additional <?php //echo $grid['cont2Col']; ?>">
                            <div class="container2-wrapper"><?php echo $container2_html; ?></div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
                
                
              
                

					

				</div>
     <?php if($productType!="simple") { ?>           
        <div class="inner">
        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/view/rightData.phtml')->setProduct($_product)->toHtml();?>
        <?php /*?> <h3 class="section-title padding-right">Payment Methods</h3>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('paymentmethods')->toHtml(); ?>
        <h3 class="section-title padding-right">Cancellation Policy</h3>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cancellation_policy')->toHtml(); ?>
        <h3 class="section-title padding-right">Replacement Policy</h3>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('replacementpolicy')->toHtml(); ?>
        <h3 class="section-title padding-right">Terms and Conditions</h3>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('termsandconditions')->toHtml(); ?>
        <?php */?>
        
        <?php
		$cmsBlockRightInfo = 'grant';
		if( $attributeSetId==21)
		{
			$cmsBlockRightInfo = 'tour_info';
		}
		echo $this->getLayout()->createBlock('cms/block')->setBlockId($cmsBlockRightInfo)->toHtml(); ?>
        </div> <?php } ?>
                
                <div class="inner">

					<?php echo $this->getChildHtml('container_product_secondary_1'); ?>

					<?php if (isset($p['secCol_1'])) echo $p['secCol_1']; ?>

					<?php if ($tmpHtml = $this->getChildHtml('product_secondary_top_placeholder')): //Brand logo ?>
						<div class="feature-wrapper bottom-border"><?php echo $tmpHtml; ?></div>
					<?php endif; ?>

					<?php if (isset($p['secCol_2'])) echo $p['secCol_2']; ?>

					<?php echo $this->getChildHtml('container_product_secondary_2'); ?>

					<?php if (isset($p['secCol_3'])) echo $p['secCol_3']; ?>

				</div>
                
                
			</div> <!-- end: product-secondary-column -->

		<?php endif; ?>

		<?php /*?><?php if ($_product->isSaleable() && $this->hasOptions()): ?>
			<?php if ($container2_html = $this->getChildChildHtml('container2', '', true, true)): ?>
				<div class="box-additional <?php echo $grid['cont2Col']; ?>">
					<div class="container2-wrapper"><?php echo $container2_html; ?></div>
				</div>
			<?php endif; ?>
		<?php endif; ?><?php */?>

	</form>
	<script type="text/javascript">
	//<![CDATA[
		var productAddToCartForm = new VarienForm('product_addtocart_form');
		productAddToCartForm.submit = function(button, url) {
			if (this.validator.validate()) {
				var form = this.form;
				var oldUrl = form.action;

				if (url) {
				   form.action = url;
				}
				var e = null;
				try {
					this.form.submit();
				} catch (e) {
				}
				this.form.action = oldUrl;
				if (e) {
					throw e;
				}

				if (button && button != 'undefined') {
					button.disabled = true;
				}
			}
		}.bind(productAddToCartForm);

		productAddToCartForm.submitLight = function(button, url){
			if(this.validator) {
				var nv = Validation.methods;
				delete Validation.methods['required-entry'];
				delete Validation.methods['validate-one-required'];
				delete Validation.methods['validate-one-required-by-name'];
				if (this.validator.validate()) {
					if (url) {
						this.form.action = url;
					}
					this.form.submit();
				}
				Object.extend(Validation.methods, nv);
			}
		}.bind(productAddToCartForm);
	//]]>


document.addEventListener("DOMContentLoaded", function () {
    if (window.location.hash === "#trainers") {
        const tab = document.getElementById("tab-trainers");
        const link = tab ? tab.querySelector("a") : null;

        // click the link if found
        if (link) {
            link.click();
        }

        // scroll to the element smoothly
        if (tab) {
            tab.scrollIntoView({ behavior: "smooth", block: "start" });
        }
    }
});

	</script>



	<?php //Lower primary column ?>
	<div class="box-additional <?php //echo $grid['lowerPrimCol']; ?> grid12-8" >

		<?php if (isset($p['lowerPrimCol_1'])) echo $p['lowerPrimCol_1']; ?>
		
		<?php echo $this->getChildHtml('product_additional_data') ?>

		<?php echo $this->getChildHtml('reviews'); //Reviews ?>

	</div> <!-- end: box-tabs -->

	<?php //Lower secondary column ?>
	<?php /*?><?php if (isset($p['lowerSecCol_2'])): ?>
		<div class="box-additional box-sidebar custom-sidebar-right <?php //echo $grid['lowerSecCol']; ?>">
			<div class="inner"><?php echo $p['lowerSecCol_2']; ?></div>
		</div>
	<?php endif; ?><?php */?>

	<?php if (isset($p['lowerPrimCol_2'])): ?>
		<div class="box-additional <?php //echo $grid['lowerPrimCol']; ?> grid12-8 "><?php echo $p['lowerPrimCol_2']; ?></div>
	<?php endif; ?>
    
   
    
  </div>  
    
    
    

</div> <!-- end: product-view -->
