<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    MMD_BankPayment
 * @copyright  Copyright (c) 2013 Ranjeet Singh
 * @copyright  Copyright (c) 2013 MMD Mage Mobile Design (http://www.magemobiledesign.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>    <?php echo $this->getMethod()->getTitle(); ?>  
    <?php if ($_customText = $this->getMethod()->getCustomText()): ?>     
    <p>    <?php echo $_customText; ?></p>
    <?php endif; ?>

